### ISSUE TITLE
Function: ENAMETOOLONG during build

### ISSUE THREAD

**Issue by racker-vikk** [sst/sst#1093]
I got this error while running `sst remove`.
```
Error: ENAMETOOLONG: name too long, mkdir '/Users/*****/Projects/*****/casa/lambdas/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2/.build/cdk.out/asset.37a0d1af8686b0315b28840e57087b7a114094ed2ed2621f67a0b9629a09dff2'
    at Object.mkdirSync (node:fs:1334:3)
    at copyDirectory (/Users/*****/Projects/*****/casa/lambdas/node_modules/@aws-cdk/core/lib/fs/copy.ts:48:10)
    at copyDirectory (/Users/*****/Projects/*****/casa/lambdas/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/*****/Projects/*****/casa/lambdas/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/*****/Projects/*****/casa/lambdas/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/*****/Projects/*****/casa/lambdas/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/*****/Projects/*****/casa/lambdas/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/*****/Projects/*****/casa/lambdas/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/*****/Projects/*****/casa/lambdas/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/*****/Projects/*****/casa/lambdas/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
```

Relevant package.json info:
```
  "scripts": {
    "start": "sst start",
    "build": "sst build",
    "deploy": "sst deploy",
    "remove": "sst remove"
  },
  "dependencies": {
    "@aws-sdk/client-ssm": "^3.33.0",
    "@aws/dynamodb-batch-iterator": "^0.7.1",
    "@aws/dynamodb-query-iterator": "^0.7.1",
    "@middy/core": "^2.5.1",
    "@middy/http-cors": "^2.5.1",
    "@middy/http-event-normalizer": "^2.5.1",
    "@middy/http-header-normalizer": "^2.5.1",
    "@middy/http-json-body-parser": "^2.5.1",
    "@sailplane/expiring-value": "^2.0.0",
    "@sailplane/injector": "^2.0.1",
    "@sailplane/lambda-utils": "^4.0.0",
    "@sailplane/logger": "^3.0.0",
    "@sailplane/state-storage": "^2.0.0",
    "bottlejs": "^1.7.2",
    "deepmerge": "^4.2.2",
    "http-errors": "^1.8.0",
    "jsonwebtoken": "^8.5.1",
    "jwk-to-pem": "^2.0.5",
    "node-fetch": "^2.6.5",
    "node-forge": "^0.10.0",
    "temporal-constants": "^1.1.2",
    "temporal-types": "^1.2.0",
    "ts-deferred": "^1.0.4",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@aws-cdk/assert": "1.132.0",
    "@aws-cdk/cloudformation-include": "1.132.0",
    "@aws-cdk/core": "1.132.0",
    "@serverless-stack/cli": "0.53.2",
    "@serverless-stack/resources": "0.53.2",
    "@types/aws-iot-device-sdk": "^2.2.3",
    "@types/aws-lambda": "^8.10.84",
    "@types/http-errors": "^1.8.1",
    "@types/jest": "^26.0.24",
    "@types/jsonwebtoken": "^8.5.5",
    "@types/jwk-to-pem": "^2.0.1",
    "@types/node-fetch": "^2.5.12",
    "@types/node-forge": "^0.10.8",
    "@types/uuid": "^8.3.1",
    "@types/ws": "^7.4.7",
    "@typescript-eslint/eslint-plugin": "^5.3.0",
    "@typescript-eslint/parser": "^5.3.0",
    "amazon-cognito-identity-js": "^4.6.3",
    "aws-iot-device-sdk": "^2.2.11",
    "aws-sdk": "^2.1030.0",
    "eslint": "^8.1.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-jest": "^25.2.2",
    "eslint-plugin-jsdoc": "^37.0.3",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "jest": "^26.6.3",
    "punycode": "^2.1.1",
    "rxjs": "^6.6.7",
    "serverless": "^2.65.0",
    "serverless-plugin-export-endpoints": "^0.1.3",
    "serverless-scriptable-plugin": "^1.2.2",
    "serverless-webpack": "^5.5.5",
    "source-map-support": "^0.5.20",
    "terser-webpack-plugin": "^5.2.5",
    "ts-jest": "^26.5.6",
    "ts-loader": "^9.2.6",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.11.0",
    "tsconfig-paths-webpack-plugin": "^3.5.1",
    "typescript": "4.2.x",
    "webpack": "^5.61.0",
    "webpack-cli": "^4.9.1",
    "ws": "^7.5.5"
  }
```
Ignore the serverless framework dependencies. I'm in mid migration to SST. I copied over relevant files from the scaffold created by `npx create-serverless-stack@latest my-app --language typescript`

**Comment by racker-vikk** [comment]
Found the issue. I had an EdgeFunction that specified the Code.fromAsset  as `./`, which seems to point to `.build/lib` instead of a the relative path of the stack file. This seems to cause some sort of recursive loop. I'm still working through getting `Code.fromAsset` to work without giving me an `ENOENT` error, but this issue can be closed.

**Comment by fwang** [comment]
Hey @racker-vikk, glad you figured it out.

Let me re-open the issue. We should throw a more description error message.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
