### ISSUE TITLE
Cannot build stack when using yarn workspaces

### ISSUE THREAD

**Issue by molnarzs** [sst/sst#1131]
Reason: the latest versions added stun as dependency,however they checked in some sources in node_modules in the source tree:

https://github.com/nodertc/stun/tree/master/src

Reason: yarn cannot resolve the packages that the stun source refers to, causing errors like:

```
Error: Cannot find module 'net/request'
Require stack:
- /home/molnarzs/ActualProjects/bgap/anyupp/apps/common-backend/.build/lib/index.js
- /home/molnarzs/ActualProjects/bgap/anyupp/apps/common-backend/.build/run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at ../../node_modules/stun/src/index.js (/home/molnarzs/ActualProjects/bgap/anyupp/node_modules/stun/src/index.js:19:21)
    at __require (/home/molnarzs/ActualProjects/bgap/anyupp/apps/common-backend/.build/lib/index.js:38:44)
    at ../../node_modules/@serverless-stack/core/dist/bridge/bridge.js (/home/molnarzs/ActualProjects/bgap/anyupp/node_modules/@serverless-stack/core/dist/bridge/bridge.js:8:32)
    at __require (/home/molnarzs/ActualProjects/bgap/anyupp/apps/common-backend/.build/lib/index.js:38:44)
    at ../../node_modules/@serverless-stack/core/dist/bridge/index.js (/home/molnarzs/ActualProjects/bgap/anyupp/node_modules/@serverless-stack/core/dist/bridge/index.js:23:31)
    at __require (/home/molnarzs/ActualProjects/bgap/anyupp/apps/common-backend/.build/lib/index.js:38:44)
```

as their request.js is in an embedded node_modules.

**Comment by 3stacks** [comment]
Same problem for me when using the NextJsSite construct. It's looking for the `next` binary in the working directory of the Next app but it's being hoisted up to the root workspace.

My repo structure is roughly like this
```
./                                                                           package.json
./primary-workspace                                            package.json *
./primary-workspace/secondary-workspace-1     package.json
./primary-workspace/secondary-workspace-2     package.json
```
In the primary workspace `package.json` I added the hoistingLimits config like this:

```
{
  "installConfig": {
    "hoistingLimits": "workspaces"
  },
  "workspaces": [...]
}
```

and now the next binary is down at the lowest level. Not sure if that will solve your problem, but it seems related.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
