### ISSUE TITLE
"TypeError: Cannot read property 'map' of undefined" when missing vue loader

### ISSUE THREAD

**Issue by gemmadlou** [sst/sst#1392]
Just logging a bug I found today. I'd gladly help to fix it if I could, but it might be resolved faster in more capable hands.

Error found here:

https://github.com/serverless-stack/serverless-stack/blob/cdfbf1d282a14f3c2076a1f03f0fdd7f54cae6b9/packages/core/src/runtime/handler/node.ts#L185

I'm not sure how the `e.errors` is meant to work, but I found that it's undefined and causes the only error that came through:

```
TypeError: Cannot read property 'map' of undefined
    at Object.build (/Users/gemma/Workspace/lincoln/node_modules/@serverless-stack/core/dist/runtime/handler/node.js:179:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Server.trigger (/Users/gemma/Workspace/lincoln/node_modules/@serverless-stack/core/dist/runtime/server.js:177:29)
    at WS.handleRequest (/Users/gemma/Workspace/lincoln/node_modules/@serverless-stack/cli/scripts/start.js:318:20)
    at WS.handleMessage (/Users/gemma/Workspace/lincoln/node_modules/@serverless-stack/core/dist/runtime/ws.js:90:26)
```

The config looks like this:

```js
{
  loader: { '.html': 'text', '.vue': 'vue' },
  minify: undefined,
  define: undefined,
  keepNames: undefined,
  entryPoints: [ 'src/functions/dashboard.js' ],
  bundle: true,
  external: [ 'aws-sdk' ],
  mainFields: [ 'main', 'module' ],
  sourcemap: true,
  platform: 'node',
  target: 'node14',
  format: 'cjs',
  outfile: '/Users/gemma/Workspace/lincoln/.sst/artifacts/dev-lincoln-my-stack-Api-Lambda_GET_-dashboard/src/functions/dashboard.js'
}
```

The error message returned wasn't highlighting the problem, but I added some console logs (node_modules/@serverless-stack/core/dist/runtime/handler/node.js) which showed this:

```
Error: Invalid loader value: "vue"
    at /Users/gemma/Workspace/lincoln/node_modules/@serverless-stack/core/node_modules/esbuild/lib/main.js:1333:25
    at /Users/gemma/Workspace/lincoln/node_modules/@serverless-stack/core/node_modules/esbuild/lib/main.js:664:9
    at handleIncomingPacket (/Users/gemma/Workspace/lincoln/node_modules/@serverless-stack/core/node_modules/esbuild/lib/main.js:759:9)
    at Socket.readFromStdout (/Users/gemma/Workspace/lincoln/node_modules/@serverless-stack/core/node_modules/esbuild/lib/main.js:631:7)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Adding an appropriate vue loader should fix the above, but the real error was getting lost.

**Comment by fwang** [comment]
Hi @gemmadlou, thanks for bringing this up. Let me give it a try and see if I can reproduce this on my end.

**Comment by monika6633** [comment]
https://github.com/serverless-stack/sst/issues/1392

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
