### ISSUE TITLE
error handling on failed cdk tasks

### ISSUE THREAD

**Issue by js-timbirkett** [sst/sst#1628]
Hi 👋

It appears that SST doesn't pass some errors back up to the user's shell when the underlying CDK task fails. 

Is this deliberate? Would it be better to exit with the code of the underlying CDK process? 

```
Run yarn sst diff --stage=nonprod
yarn run v1.22.18
$ /home/runner/work/b2bgifting-bootstrap/b2bgifting-bootstrap/node_modules/.bin/sst diff --stage=nonprod
Using stage: nonprod
Preparing your SST app

Error: nonprod-b2bgifting-bootstrap-default-vpc/DefaultSG/to [12](https://github.com/sainsburys-tech/b2bgifting-bootstrap/runs/6025606195?check_suite_focus=true#step:7:12)7.0.0.1_32:9 [AWS::EC2::SecurityGroupEgress] is missing required property: groupId
    at Object.requireProperty (/home/runner/work/b2bgifting-bootstrap/b2bgifting-bootstrap/node_modules/aws-cdk-lib/core/lib/runtime.ts:338:11)
    at new CfnSecurityGroupEgress (/home/runner/work/b2bgifting-bootstrap/b2bgifting-bootstrap/node_modules/aws-cdk-lib/aws-ec2/lib/ec2.generated.ts:21934:[13](https://github.com/sainsburys-tech/b2bgifting-bootstrap/runs/6025606195?check_suite_focus=true#step:7:13))
    at MutableImport.addEgressRule (/home/runner/work/b2bgifting-bootstrap/b2bgifting-bootstrap/node_modules/aws-cdk-lib/aws-ec2/lib/security-group.ts:110:7)
    at MutableImport.addEgressRule (/home/runner/work/b2bgifting-bootstrap/b2bgifting-bootstrap/node_modules/aws-cdk-lib/aws-ec2/lib/security-group.ts:367:17)
    at new DefaultVpc (/home/runner/work/b2bgifting-bootstrap/b2bgifting-bootstrap/stacks/DefaultVpc.js:18:26)
    at Object.main (/home/runner/work/b2bgifting-bootstrap/b2bgifting-bootstrap/stacks/index.js:15:3)
    at Object.<anonymous> (/home/runner/work/b2bgifting-bootstrap/b2bgifting-bootstrap/.build/run.js:94:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:[14](https://github.com/sainsburys-tech/b2bgifting-bootstrap/runs/6025606195?check_suite_focus=true#step:7:14))
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[15](https://github.com/sainsburys-tech/b2bgifting-bootstrap/runs/6025606195?check_suite_focus=true#step:7:15)7:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)


Subprocess exited with error 1
````

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
