### ISSUE TITLE
TypeError: this[#visitors][node.kind] is not a function

### ISSUE THREAD

**Issue by ColinOrr** [sst/sst#2080]
Hi Folks 👋 

I'm trying to run through the guide on your website, and I'm getting this error when I run `npx sst start`:

```
==========================
 Starting Live Lambda Dev
==========================

SST Console: https://console.sst.dev/my-sst-app/colin/local
Debug session started. Listening for requests...

TypeError: this[#visitors][node.kind] is not a function
    at PostgresDataApiQueryCompiler.visitNode (file:///Users/colin/code/my-sst-app/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:81:34)
    at PostgresDataApiQueryCompiler.visitTable (file:///Users/colin/code/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:308:14)
    at PostgresDataApiQueryCompiler.visitNode (file:///Users/colin/code/my-sst-app/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:81:34)
    at PostgresDataApiQueryCompiler.visitReference (file:///Users/colin/code/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:215:14)
```

Here's the section of the guide I'm working on:

https://docs.sst.dev/learn/initialize-the-database

As instructed, I'm using Node 14, but I've also tried it at v16 and v18.

**Comment by igalklebanov** [comment]
Hey :wave:

This issue is due to conflicting versions of [kysely](https://github.com/koskimas/kysely) existing in the project's node_modules.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
