### ISSUE TITLE
Bug: sst deploy --role-arn not assuming correct role

### ISSUE THREAD

**Issue by bestickley** [sst/sst#2233]
Hi, when I run `sst deploy --stage "pkh-sand01-applications" --role-arn "arn:aws:iam::102258469230:role/cdk-pkhdev-deploy-role-102258469230-us-east-1"`, sst does not correctly assume the role I pass it. SST is trying to use the default cdk role. Referencing below output, why is sst trying to assume `'arn:aws:iam::102258469230:role/cdk-hnb659fds-deploy-role-102258469230-us-east-1'` and not the role I passed?

```bash
[16:49:31] Could not assume role in target account using current credentials User: arn:aws:sts::102258469230:assumed-role/cdk-pkhdev-deploy-role-102258469230-us-east-1/PKHSession is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::102258469230:role/cdk-hnb659fds-deploy-role-102258469230-us-east-1 . Please make sure that this role exists in the account. If it doesn't exist, (re)-bootstrap the environment with the right '--trust', using the latest version of the CDK CLI.
current credentials could not be used to assume 'arn:aws:iam::102258469230:role/cdk-hnb659fds-deploy-role-102258469230-us-east-1', but are for the right account. Proceeding anyway.
```

Is this a bug with SST or am I using assume role incorrectly?

Full Verbose Output:
```
pnpm sst deploy --stage "pkh-sand01-applications" --role-arn "arn:aws:iam::102258469230:role/cdk-pkhdev-deploy-role-102258469230-us-east-1" --verbose
It is highly recommended to set `predictableActionArguments` to `true` when using `createMachine`. https://xstate.js.org/docs/guides/actions.html
SST: 1.18.4
CDK: 2.50.0
Determining if we're on an EC2 instance.
Does not look like an EC2 instance.
Using stage: pkh-sand01-applications
Preparing your SST app

Mismatched versions of AWS CDK packages. SST currently supports 2.50.0. Fix using:

  npm install aws-cdk-lib@2.50.0 --save-dev --save-exact

Learn more about it here — https://docs.sst.dev/known-issues

Bootstrapping SST in the "us-east-1" region
synth {
  app: 'node bin/index.mjs us-east-1 e30=',
  output: 'cdk.out',
  rollback: true,
  roleArn: 'arn:aws:iam::102258469230:role/cdk-pkhdev-deploy-role-102258469230-us-east-1',
  verbose: 2,
  noColor: false
}
[16:49:25] CDK toolkit version: 2.50.0 (build 4c11af6)
[16:49:25] Command line arguments: {
  _: [ 'synth' ],
  'version-reporting': false,
  versionReporting: false,
  app: 'node bin/index.mjs us-east-1 e30=',
  a: 'node bin/index.mjs us-east-1 e30=',
  output: 'cdk.out',
  o: 'cdk.out',
  quiet: true,
  q: true,
  'role-arn': 'arn:aws:iam::102258469230:role/cdk-pkhdev-deploy-role-102258469230-us-east-1',
  r: 'arn:aws:iam::102258469230:role/cdk-pkhdev-deploy-role-102258469230-us-east-1',
  roleArn: 'arn:aws:iam::102258469230:role/cdk-pkhdev-deploy-role-102258469230-us-east-1',
  verbose: 1,
  v: 1,
  defaultAccount: 102258469230,
  disableVersionCheck: 'true',
  lookups: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  debug: false,
  ec2creds: undefined,
  i: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  staging: true,
  'no-color': false,
  noColor: false,
  ci: false,
  validation: true,
  '$0': '../../../../../../../aws-cdk@2.50.0/node_modules/aws-cdk/bin/cdk'
}
[16:49:25] cdk.json: {
  "app": "node bin/index.js",
  "context": {
    "aws-cdk:enableDiffNoFail": "true"
  }
}
[16:49:25] merged settings: {
  versionReporting: false,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'node bin/index.mjs us-east-1 e30=',
  context: { 'aws-cdk:enableDiffNoFail': 'true' },
  debug: false,
  assetMetadata: true,
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [ '**' ],
  lookups: true
}
[16:49:25] Determining if we're on an EC2 instance.
[16:49:25] Does not look like an EC2 instance.
[16:49:25] Reading cached notices from /Users/stickb/.cdk/cache/notices.json
[16:49:25] Toolkit stack: CDKToolkit
[16:49:25] Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
[16:49:25] Resolving default credentials
[16:49:25] Retrieved account ID 102258469230 from disk cache
[16:49:25] Setting "CDK_DEFAULT_ACCOUNT" environment variable to 102258469230
[16:49:25] context: {
  'aws-cdk:enableDiffNoFail': 'true',
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
  'aws:cdk:disable-version-reporting': true,
  'aws:cdk:bundling-stacks': [ '**' ]
}
[16:49:25] outdir: cdk.out
[16:49:26] env: {
  CDK_DEFAULT_REGION: 'us-east-1',
  CDK_DEFAULT_ACCOUNT: '102258469230',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '21.0.0',
  CDK_CLI_VERSION: '2.50.0'
}
It is highly recommended to set `predictableActionArguments` to `true` when using `createMachine`. https://xstate.js.org/docs/guides/actions.html
[16:49:29] Reading cached notices from /Users/stickb/.cdk/cache/notices.json

checkInReviewBootstrapStacks
checkInReviewBootstrapStackInRegion us-east-1
deploy stack: started SSTBootstrap
deploy stack: get pre-deploy status
deploy stack: get pre-deploy status: stack does not exist
deploy stack: addInUseExports
deploy stack: isTemplateChanged
deploy stack: run cdk deploy
deploy stack: poll stack status
deploy stack: poll stack status: unknown
deploy stack: run cdk deploy: exited with code 1
deploy stack: poll stack status: cp exited
[16:49:31] CDK toolkit version: 2.50.0 (build 4c11af6)
[16:49:31] Command line arguments: {
  _: [ 'deploy' ],
  'version-reporting': false,
  versionReporting: false,
  app: 'cdk.out',
  a: 'cdk.out',
  rollback: true,
  exclusively: true,
  e: true,
  'require-approval': 'never',
  requireApproval: 'never',
  execute: true,
  'role-arn': 'arn:aws:iam::102258469230:role/cdk-pkhdev-deploy-role-102258469230-us-east-1',
  r: 'arn:aws:iam::102258469230:role/cdk-pkhdev-deploy-role-102258469230-us-east-1',
  roleArn: 'arn:aws:iam::102258469230:role/cdk-pkhdev-deploy-role-102258469230-us-east-1',
  verbose: 1,
  v: 1,
  defaultAccount: 102258469230,
  disableVersionCheck: 'true',
  lookups: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  debug: false,
  ec2creds: undefined,
  i: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  staging: true,
  'no-color': false,
  noColor: false,
  ci: false,
  all: false,
  'build-exclude': [],
  E: [],
  buildExclude: [],
  force: false,
  f: false,
  parameters: [ {} ],
  'previous-parameters': true,
  previousParameters: true,
  logs: true,
  concurrency: 1,
  '$0': '../../../../../../../aws-cdk@2.50.0/node_modules/aws-cdk/bin/cdk',
  STACKS: [ 'SSTBootstrap' ],
  'S-t-a-c-k-s': [ 'SSTBootstrap' ]
}
[16:49:31] cdk.json: {
  "app": "node bin/index.js",
  "context": {
    "aws-cdk:enableDiffNoFail": "true"
  }
}
[16:49:31] merged settings: {
  versionReporting: false,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'cdk.out',
  context: { 'aws-cdk:enableDiffNoFail': 'true' },
  debug: false,
  assetMetadata: true,
  requireApproval: 'never',
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [ 'SSTBootstrap' ],
  lookups: true,
  rollback: true
}
[16:49:31] Determining if we're on an EC2 instance.
[16:49:31] Does not look like an EC2 instance.
[16:49:31] Reading cached notices from /Users/stickb/.cdk/cache/notices.json
[16:49:31] Toolkit stack: CDKToolkit
[16:49:31] Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
[16:49:31] Resolving default credentials
[16:49:31] Retrieved account ID 102258469230 from disk cache
[16:49:31] Setting "CDK_DEFAULT_ACCOUNT" environment variable to 102258469230
[16:49:31] context: {
  'aws-cdk:enableDiffNoFail': 'true',
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
  'aws:cdk:disable-version-reporting': true,
  'aws:cdk:bundling-stacks': [ 'SSTBootstrap' ]
}
[16:49:31] --app points to a cloud assembly, so we bypass synth

✨  Synthesis time: 0.02s

SSTBootstrap: building assets...

[16:49:31] Retrieved account ID 102258469230 from disk cache
[16:49:31] Assuming role 'arn:aws:iam::102258469230:role/cdk-hnb659fds-deploy-role-102258469230-us-east-1'.
[16:49:31] Assuming role failed: User: arn:aws:sts::102258469230:assumed-role/cdk-pkhdev-deploy-role-102258469230-us-east-1/PKHSession is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::102258469230:role/cdk-hnb659fds-deploy-role-102258469230-us-east-1
[16:49:31] Could not assume role in target account using current credentials User: arn:aws:sts::102258469230:assumed-role/cdk-pkhdev-deploy-role-102258469230-us-east-1/PKHSession is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::102258469230:role/cdk-hnb659fds-deploy-role-102258469230-us-east-1 . Please make sure that this role exists in the account. If it doesn't exist, (re)-bootstrap the environment with the right '--trust', using the latest version of the CDK CLI.
current credentials could not be used to assume 'arn:aws:iam::102258469230:role/cdk-hnb659fds-deploy-role-102258469230-us-east-1', but are for the right account. Proceeding anyway.
[16:49:31] Waiting for stack CDKToolkit to finish creating or updating...
[16:49:31] Call failed: getParameter({"Name":"/cdk-bootstrap/hnb659fds/version"}) => User: arn:aws:sts::102258469230:assumed-role/cdk-pkhdev-deploy-role-102258469230-us-east-1/PKHSession is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:102258469230:parameter/cdk-bootstrap/hnb659fds/version because no identity-based policy allows the ssm:GetParameter action (code=AccessDeniedException)

 ❌ Building assets failed: Error: Building Assets Failed: Error: SSTBootstrap: User: arn:aws:sts::102258469230:assumed-role/cdk-pkhdev-deploy-role-102258469230-us-east-1/PKHSession is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:102258469230:parameter/cdk-bootstrap/hnb659fds/version because no identity-based policy allows the ssm:GetParameter action
    at buildAllStackAssets (/Users/stickb/Code/pkh/StarterRepo/node_modules/.pnpm/aws-cdk@2.50.0/node_modules/aws-cdk/lib/build.ts:21:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/Users/stickb/Code/pkh/StarterRepo/node_modules/.pnpm/aws-cdk@2.50.0/node_modules/aws-cdk/lib/cdk-toolkit.ts:175:7)
    at initCommandLine (/Users/stickb/Code/pkh/StarterRepo/node_modules/.pnpm/aws-cdk@2.50.0/node_modules/aws-cdk/lib/cli.ts:358:12)
[16:49:31] Reading cached notices from /Users/stickb/.cdk/cache/notices.json

Building Assets Failed: Error: SSTBootstrap: User: arn:aws:sts::102258469230:assumed-role/cdk-pkhdev-deploy-role-102258469230-us-east-1/PKHSession is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:102258469230:parameter/cdk-bootstrap/hnb659fds/version because no identity-based policy allows the ssm:GetParameter action
[16:49:31] Error: Building Assets Failed: Error: SSTBootstrap: User: arn:aws:sts::102258469230:assumed-role/cdk-pkhdev-deploy-role-102258469230-us-east-1/PKHSession is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:102258469230:parameter/cdk-bootstrap/hnb659fds/version because no identity-based policy allows the ssm:GetParameter action
    at buildAllStackAssets (/Users/stickb/Code/pkh/StarterRepo/node_modules/.pnpm/aws-cdk@2.50.0/node_modules/aws-cdk/lib/build.ts:21:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/Users/stickb/Code/pkh/StarterRepo/node_modules/.pnpm/aws-cdk@2.50.0/node_modules/aws-cdk/lib/cdk-toolkit.ts:175:7)
    at initCommandLine (/Users/stickb/Code/pkh/StarterRepo/node_modules/.pnpm/aws-cdk@2.50.0/node_modules/aws-cdk/lib/cli.ts:358:12)
deploy stack: done SSTBootstrap {
  status: 'failed',
  statusReason: undefined,
  account: undefined,
  outputs: undefined,
  exports: undefined
}

 ❌  SSTBootstrap failed: The SSTBootstrap stack failed to deploy.

deployRet [
  {
    id: 'SSTBootstrap',
    name: 'SSTBootstrap',
    region: 'us-east-1',
    status: 'failed',
    errorHelper: undefined,
    errorMessage: 'The SSTBootstrap stack failed to deploy.',
    outputs: undefined,
    exports: undefined
  }
]

Stack SSTBootstrap
  Error: The SSTBootstrap stack failed to deploy.

Failed to run SST bootstrap.
```

**Comment by irwing-reza** [comment]
any updates on this??

**Comment by bestickley** [comment]
@irwing-reza, no updates from me. I had to revert to using vanilla AWS CDK based on my team's restrictions.

**Comment by thdxr** [comment]
do you have this issue in sst2 as well?

**Comment by bestickley** [comment]
@thdxr, I have not. @irwing-reza, could you try with sst2?

**Comment by jayair** [comment]
Btw, the option has been renamed to `--role` in sst2. Can you try that?

**Comment by irwing-reza** [comment]
with --role i get 

```
synth {
  app: 'node bin/index.mjs us-east-1 e30=',
  output: 'cdk.out',
  rollback: true,
  roleArn: undefined,
  verbose: 2,
  noColor: false
}
```

using --role-arn

```
synth {
  app: 'node bin/index.mjs us-east-1 e30=',
  output: 'cdk.out',
  rollback: true,
  roleArn: 'arn:aws:iam::72342023:role/DeploymentRole',
  verbose: 2,
  noColor: false
}

```
but neither works it always try to assume another role

**Comment by thdxr** [comment]
is this in sst2? it should work

**Comment by jiby-aurum** [comment]
@thdxr does not work for me, I see in the logs the correct role as configured in set config, however in log line for `Using identity Account` it still shows the root account

**Comment by jayair** [comment]
@jiby-aurum Can you open a new thread in #help on Discord?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
