### ISSUE TITLE
Error TooManyUpdates when using Config.Secret

### ISSUE THREAD

**Issue by mortkarlberg** [sst/sst#2268]
I have started getting intermittent errors at first deployments when using _new Config.Secret(stack, "MY_SECRET")_. The error is "TooManyUpdates: null" in random (non-related) stacks when I run "sst start". If I run "sst start" again, deployment works fine. If I then run "stt remove" followed by "sst start", I get the error again.

I think the error started happening after upgrading from sst v. 1.15 to 1.18.4 and started using resource binding, but I'm not 100% sure.

I was not able to reproduce the errors in a new project. When digging deeper in Parameter Store I found duplicate parameters with almost the same names, for example: "/sst/my-app/.fallback/Secret/MY_SECRET/value" vs. "/sst/my-app/.fallback/secrets/MY_SECRET". First deployment works as expected after deleting the second parameter.

Full error:

2022-12-16T09:29:37.522Z	3ff13993-53c4-49b4-9f8b-993b46784b3d	INFO	[AWS ssm 400 0.052s 0 retries] putParameter({
  Name: '/sst/my-app/.fallback/Secret/MY_SECRET/value',
  Value: '***SensitiveInformation***',
  Type: 'SecureString',
  Overwrite: true
})

2022-12-16T09:29:37.523Z	3ff13993-53c4-49b4-9f8b-993b46784b3d	INFO	[provider-framework] TooManyUpdates: null
    at Object.extractError (file:///var/task/index.mjs:47:95912)
    at Object.callListeners (file:///var/task/index.mjs:47:137006)
    at Object.emit (file:///var/task/index.mjs:47:136681)
    at Object.emit (file:///var/task/index.mjs:48:29428)
    at Object.transition (file:///var/task/index.mjs:48:24697)
    at BL.runTo (file:///var/task/index.mjs:48:1201)
    at file:///var/task/index.mjs:48:1413
    at Object.<anonymous> (file:///var/task/index.mjs:48:24912)
    at Object.<anonymous> (file:///var/task/index.mjs:48:29483)
    at Object.callListeners (file:///var/task/index.mjs:47:137111) {
  code: 'TooManyUpdates',
  time: 2022-12-16T09:29:37.521Z,
  requestId: '84c5f518-f6c4-4dbd-bab1-da2c64f9c039',
  statusCode: 400,
  retryable: false,
  retryDelay: 3000
}

**Comment by thdxr** [comment]
We have this fixed in 2.0

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
