### ISSUE TITLE
Error running migration from learn tutorial

### ISSUE THREAD

**Issue by srjheam** [sst/sst#2321]
Hi,

The default migration in the SST Learn tutorial has a problem. Every time I try to apply the articles migration, it results in `Error: invalid immediate value [object Object]`.

## SST start log
```
Using stage: sst-learn
Preparing your SST app

=======================
 Deploying debug stack
=======================


Deploying stacks

 ✅  sst-learn-my-sst-app-debug-stack (no changes)


Stack sst-learn-my-sst-app-debug-stack
  Status: no changes
  Outputs:
    BucketArn: arn:aws:s3:::sst-learn-my-sst-app-debug-stack-bucket******-******
    BucketName: sst-learn-my-sst-app-debug-stack-bucket******-******
    Endpoint: wss://******.execute-api.us-east-1.amazonaws.com/sst-learn


===============
 Deploying app
===============


Deploying stacks

 ✅  sst-learn-my-sst-app-Database (no changes)


 ✅  sst-learn-my-sst-app-Api (no changes)


 ✅  sst-learn-my-sst-app-Web (no changes)


Stack sst-learn-my-sst-app-Database
  Status: no changes

Stack sst-learn-my-sst-app-Api
  Status: no changes
  Outputs:
    API: https://******.execute-api.us-east-1.amazonaws.com

Stack sst-learn-my-sst-app-Web
  Status: no changes
  Outputs:
    SITE: https://******.cloudfront.net


==========================
 Starting Live Lambda Dev
==========================

SST Console: https://console.sst.dev/my-sst-app/sst-learn/local
Debug session started. Listening for requests...
Done building pothos schema
976d89fd-cd83-4252-95eb-8a1e32583e88 REQUEST sst-learn-my-sst-app-Api-apiLambdaPOSTgraphql9D0A1-v00zlWocqiYs [functions/graphql/graphql.handler] invoked by API POST /graphql
976d89fd-cd83-4252-95eb-8a1e32583e88 RESPONSE {"statusCode":200,"body":"{\"errors\":[{\"message\":\"this[#visitors][node.kind] is not a function\",\"locations\":[{\"line\":2,\"column\"... 38 more characters","headers":{"Content-Type":"application/json"}}
f072e737-a8d9-4c29-80c1-915351c8d4b4 REQUEST sst-learn-my-sst-app-Data-dbMigrationFunction7BEAF-bR40ngDfbyD1 [index.handler] invoked
f072e737-a8d9-4c29-80c1-915351c8d4b4 RESPONSE [{"name":"1650000012557_article","migration":{}}]
67b33067-2d87-4849-9fcd-0f4e865af256 REQUEST sst-learn-my-sst-app-Data-dbMigrationFunction7BEAF-bR40ngDfbyD1 [index.handler] invoked
67b33067-2d87-4849-9fcd-0f4e865af256 RESPONSE [{"name":"1650000012557_article","migration":{}}]
9f68f547-e454-412b-a8f3-84d07570c962 REQUEST sst-learn-my-sst-app-Data-dbMigrationFunction7BEAF-bR40ngDfbyD1 [index.handler] invoked
1fc1b0dc-6f4d-4b7e-8d7d-1af53a9afd90 REQUEST sst-learn-my-sst-app-Data-dbMigrationFunction7BEAF-bR40ngDfbyD1 [index.handler] invoked
9f68f547-e454-412b-a8f3-84d07570c962 ERROR Error: invalid immediate value [object Object] 
 Error: invalid immediate value [object Object]
    at PostgresDataApiQueryCompiler.appendImmediateValue (file:///home/srjheam/projects/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:934:19)
    at PostgresDataApiQueryCompiler.visitValue (file:///home/srjheam/projects/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:266:18)
    at PostgresDataApiQueryCompiler.visitNode (file:///home/srjheam/projects/my-sst-app/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
    at PostgresDataApiQueryCompiler.visitDefaultValue (file:///home/srjheam/projects/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:824:14)
    at PostgresDataApiQueryCompiler.visitNode (file:///home/srjheam/projects/my-sst-app/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
    at PostgresDataApiQueryCompiler.visitColumnDefinition (file:///home/srjheam/projects/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:367:18)
    at PostgresDataApiQueryCompiler.visitNode (file:///home/srjheam/projects/my-sst-app/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
    at PostgresDataApiQueryCompiler.compileList (file:///home/srjheam/projects/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:116:18)
    at PostgresDataApiQueryCompiler.visitCreateTable (file:///home/srjheam/projects/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:343:14)
    at PostgresDataApiQueryCompiler.visitNode (file:///home/srjheam/projects/my-sst-app/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
```

## Migration
```mjs
import { Kysely, sql } from "kysely";

/**
 * @param db {Kysely<any>}
 */
export async function up(db) {
  await db.schema
    .createTable("article")
    .addColumn("articleID", "text", col => col.primaryKey())
    .addColumn("title", "text", col => col.notNull())
    .addColumn("url", "text", col => col.notNull())
    .addColumn("created", "timestamp", col =>
      col.notNull().defaultTo(sql`now()`)
    )
    .execute();

  await db.schema
    .createIndex("idx_article_created")
    .on("article")
    .column("created")
    .execute();
}

/**
 * @param db {Kysely<any>}
 */
export async function down(db) {
  await db.schema.dropIndex("idx_article_created").execute();
  await db.schema.dropTable("article").execute();
}
```

I'm aware of #2129 , but doing the opposite of it did not solve the problem.

Thanks in advance.

**Comment by srjheam** [comment]
As a workaround, changing `` sql`now()` `` to whatever hardcoded value should allow you to apply the migration.

```mjs
.addColumn("created", "timestamp", (col) =>
  col.notNull().defaultTo("1000-01-01 00:00:00")
)
```

**Comment by chromosomaly** [comment]
+1 @srjheam thanks for the workaround

**Comment by hermano360** [comment]
I am seeing this as well. It seems in the kysely code, it's not able to convert that RawBuilder into a string.

**Comment by andykenward** [comment]
Still getting this error when using `create-sst` 1.18.4  and following [Run a migration](https://docs.sst.dev/learn/initialize-the-database#run-a-migration).

It appears to be the `kysely` npm packages version changes and mismatch in other npm packages. As the guide, [video](https://www.youtube.com/watch?v=i7xEKHWTKNk), `create-sst@1.18.4` and the repo [`tutorial-links-app`](https://github.com/serverless-stack/tutorial-links-app/blob/4703f3160a814202227fa47ea26bda5b658c30c1/package.json#L15-L23) use different versions of npm packages.

Would it be worth using exact npm package versions? Along with defining the [engines](https://docs.npmjs.com/cli/v8/configuring-npm/package-json?v=true#engines) it supports? This may reduce others running into these issues in the future?

Have a look at how `create-next-app` has managed their [npm packages](https://github.com/vercel/next.js/blob/b386f680cc67749d576a28cdf21a3dca20c431b0/packages/create-next-app/package.json#L31-L58)

**Comment by jayair** [comment]
I think this is fixed in v2 but we might have to lock the versions for more complicated templates like these.

**Comment by shanu55444** [comment]
Error after running default migration, 

However this https://github.com/serverless-stack/sst/issues/2321#issuecomment-1378161640 did make me run the migration.

Error: invalid immediate value [object Object] 
 Error: invalid immediate value [object Object]
    at PostgresDataApiQueryCompiler.appendImmediateValue (file:///Users/shanusharma/example-sst/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:934:19)
    at PostgresDataApiQueryCompiler.visitValue (file:///Users/shanusharma/example-sst/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:266:18)
    at PostgresDataApiQueryCompiler.visitNode (file:///Users/shanusharma/example-sst/my-sst-app/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
    at PostgresDataApiQueryCompiler.visitDefaultValue (file:///Users/shanusharma/example-sst/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:824:14)
    at PostgresDataApiQueryCompiler.visitNode (file:///Users/shanusharma/example-sst/my-sst-app/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
    at PostgresDataApiQueryCompiler.visitColumnDefinition (file:///Users/shanusharma/example-sst/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:367:18)
    at PostgresDataApiQueryCompiler.visitNode (file:///Users/shanusharma/example-sst/my-sst-app/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
    at PostgresDataApiQueryCompiler.compileList (file:///Users/shanusharma/example-sst/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:116:18)
    at PostgresDataApiQueryCompiler.visitCreateTable (file:///Users/shanusharma/example-sst/my-sst-app/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:343:14)
    at PostgresDataApiQueryCompiler.visitNode (file:///Users/shanusharma/example-sst/my-sst-app/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
215677b0-2366-4489-bba2-aa24d2f1fefd REQUEST shanu-local-dev-my-sst-ap-dbMigrationFunction7BEAF-28Uzf6Zk6PZG [index.handler] invoked
215677b0-2366-4489-bba2-aa24d2f1fefd RESPONSE [{"name":"1650000012557_article","migration":{}}]

**Comment by tomellwood-github** [comment]
It would be good to have exact version numbers for packages used. This tutorial isn't really possible to follow along as it currently is.

There are a couple of issues with GraphQL too, had to downgrade @genql/cli from version 3 to 2 to get it kind of working.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
