### ISSUE TITLE
SST2: Rebuild on save stops working after a build error

### ISSUE THREAD

**Issue by estyrke** [sst/sst#2393]
I accidentally saved a stack file with syntax errors. After fixing the error, the build is not triggered anymore on save. This is on rc56.

```
2023-01-29T18:35:58.997Z +44291ms [debug] Publishing event {"type":"file.changed","properties":{"file":"/Users/emilst/Code/lkss/internwebb/stacks/Web.ts","relative":"stacks/Web.ts"},"sourceID":"a7592dd664190e4d0b3dc4ffc128618c"}
✖  Building...
   Error: Build failed with 1 error:
   stacks/Web.ts:55:4: ERROR: Expected "}" but found "environment"
       at failureErrorWithLog (/Users/emilst/Code/lkss/internwebb/node_modules/sst/node_modules/esbuild/lib/main.js:1596:15)
       at /Users/emilst/Code/lkss/internwebb/node_modules/sst/node_modules/esbuild/lib/main.js:1052:28
       at /Users/emilst/Code/lkss/internwebb/node_modules/sst/node_modules/esbuild/lib/main.js:997:67
       at buildResponseToResult (/Users/emilst/Code/lkss/internwebb/node_modules/sst/node_modules/esbuild/lib/main.js:1050:7)
       at /Users/emilst/Code/lkss/internwebb/node_modules/sst/node_modules/esbuild/lib/main.js:1162:14
       at responseCallbacks.<computed> (/Users/emilst/Code/lkss/internwebb/node_modules/sst/node_modules/esbuild/lib/main.js:697:9)
       at handleIncomingPacket (/Users/emilst/Code/lkss/internwebb/node_modules/sst/node_modules/esbuild/lib/main.js:752:9)
       at Socket.readFromStdout (/Users/emilst/Code/lkss/internwebb/node_modules/sst/node_modules/esbuild/lib/main.js:673:7)
       at Socket.emit (node:events:513:28)
       at Socket.emit (node:domain:489:12)
       at addChunk (node:internal/streams/readable:324:12)
       at readableAddChunk (node:internal/streams/readable:297:9)
       at Readable.push (node:internal/streams/readable:234:10)
       at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

[... here I fix the error and save again ...]

2023-01-29T18:36:04.841Z  +5844ms [debug] Publishing event {"type":"file.changed","properties":{"file":"/Users/emilst/Code/lkss/internwebb/stacks/Web.ts","relative":"stacks/Web.ts"},"sourceID":"a7592dd664190e4d0b3dc4ffc128618c"}
2023-01-29T18:36:04.942Z   +101ms [debug] Publishing event {"type":"file.changed","properties":{"file":"/Users/emilst/Code/lkss/internwebb/stacks/Web.ts","relative":"stacks/Web.ts"},"sourceID":"a7592dd664190e4d0b3dc4ffc128618c"}
´´´

**Comment by pregnantboy** [comment]
facing this issue as well. any updates on this?
