### ISSUE TITLE
StaticConstruct - Cannot read properties of undefined (reading 'outputs')

### ISSUE THREAD

**Issue by MichaelMjc** [sst/sst#2558]
Getting this error when working with the  StaticSite Construct.  

`Error: Cannot read properties of undefined (reading 'outputs')`

Weirdly it only happens if I set the environment variables in the construct.

Here's the full error

```
Trace: TypeError: Cannot read properties of undefined (reading 'outputs')
    at deploy (file:///home/michael/projects/vidstep/node_modules/.pnpm/sst@2.0.35/node_modules/sst/cli/commands/dev.js:185:37)
    at process.<anonymous> (file:///home/michael/projects/vidstep/node_modules/.pnpm/sst@2.0.35/node_modules/sst/cli/sst.js:58:17)
    at process.emit (node:events:525:35)
    at process.processEmit [as emit] (/home/michael/projects/vidstep/node_modules/.pnpm/signal-exit@3.0.7/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (node:internal/process/execution:149:25)
at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
