### ISSUE TITLE
Prisma example is broken since SST 2.0

### ISSUE THREAD

**Issue by SchmellaKaa** [sst/sst#2667]
I tried to setup a new project using the prisma example, but it does not seem to work with sst2.0

Command: `yarn create sst --template=examples/prisma`

When running a function that uses a prismaClient instance you receive an error: `Your schema.prisma could not be found, and we detected that you are using Next.js` 
I assume this is because sst is now a monorepo and prisma has some issues with monorepos and needs a workaround to function with nextjs as discussed in their documentation: https://www.prisma.io/docs/guides/database/troubleshooting-orm/help-articles/nextjs-prisma-client-monorepo#problem

**Comment by jayair** [comment]
Oh I see. What's the error you are getting btw?

**Comment by SchmellaKaa** [comment]
```
 Invoked packages/functions/src/index.handler
|  +308ms  /home/user/projects/test/node_modules/@prisma/client/runtime/library.js:99
|  +309ms  `,new G(i,this.config.clientVersion)}return this.platform=this.platform??await We(),t}async resolveEnginePath(){let searchedLocations=[],enginePath;if(this.libQueryEnginePath)return{enginePath:this.libQueryEnginePath,searchedLocations};if(this.platform=this.platform??await We(),__filename.includes("DefaultLibraryLoader"))return enginePath=ft.default.join($a(),Er(this.platform,"fs")),{enginePath,searchedLocations};let dirname=eval("__dirname"),searchLocations=[ft.default.resolve(dirname,"../../../.prisma/client"),this.config.generator?.output?.value??dirname,ft.default.resolve(dirname,".."),ft.default.dirname(this.config.datamodelPath),this.config.cwd,"/tmp/prisma-engines"];this.config.dirname&&searchLocations.push(this.config.dirname);for(let e of searchLocations)if(searchedLocations.push(e),Cl(`Searching for Query Engine Library in ${e}`),enginePath=ft.default.join(e,Er(this.platform,"fs")),Ut.default.existsSync(enginePath))return{enginePath,searchedLocations};return enginePath=ft.default.join(__dirname,Er(this.platform,"fs")),{enginePath,searchedLocations}}getFixedGenerator(){let e={...this.config.generator,binaryTargets:Qa(this.config.generator.binaryTargets,this.platform)};return el(e)}};l(Fr,"DefaultLibraryLoader");var Gd=U("prisma:client:libraryEngine:exitHooks"),Dr=class{constructor(){this.nextOwnerId=1;this.ownerToIdMap=new WeakMap;this.idToListenerMap=new Map;this.areHooksInstalled=!1}install(){this.areHooksInstalled||(this.installHook("beforeExit"),this.installHook("exit"),this.installHook("SIGINT",!0),this.installHook("SIGUSR2",!0),this.installHook("SIGTERM",!0),this.areHooksInstalled=!0)}setListener(t,r){if(r){let n=this.ownerToIdMap.get(t);n||(n=this.nextOwnerId++,this.ownerToIdMap.set(t,n)),this.idToListenerMap.set(n,r)}else{let n=this.ownerToIdMap.get(t);n!==void 0&&(this.ownerToIdMap.delete(t),this.idToListenerMap.delete(n))}}getListener(t){let r=this.ownerToIdMap.get(t);if(r!==void 0)return this.idToListenerMap.get(r)}installHook(t,r=!1){process.once(t,async n=>{Gd(`exit event received: ${t}`);for(let i of this.idToListenerMap.values())await i();this.idToListenerMap.clear(),r&&process.listenerCount(t)===0&&process.exit(n)})}};l(Dr,"ExitHooks");var je=U("prisma:client:libraryEngine");function Vd(e){return e.item_type==="query"&&"query"in e}l(Vd,"isQueryEvent");function Qd(e){return"level"in e?e.level==="error"&&e.message==="PANIC":!1}l(Qd,"isPanicEvent");var Rl=[...eo,"native"],Nl=0,fo=new Dr,Vt=class extends Ye{constructor(r,n=new Fr(r)){super();try{this.datamodel=Il.default.readFileSync(r.datamodelPath,"utf-8")}catch(i){throw i.stack.match(/\/\.next|\/next@|\/next\//)?new G(`Your schema.prisma could not be found, and we detected that you are using Next.js.
|  +309ms                                                                                                                                                                                                                                                                                         ^
|  +309ms  
|  +309ms  ReferenceError: __filename is not defined
|  +309ms      at Object.resolveEnginePath (/home/user/projects/test/node_modules/@prisma/client/runtime/library.js:99:280)
|  +309ms      at Object.getLibQueryEnginePath (/home/user/projects/test/node_modules/@prisma/client/runtime/library.js:73:1125)
|  +309ms      at Object.loadLibrary (/home/user/projects/test/node_modules/@prisma/client/runtime/library.js:73:561)
|  +309ms      at Object.loadEngine (/home/user/projects/test/node_modules/@prisma/client/runtime/library.js:101:557)
|  +309ms      at Object.instantiateLibrary (/home/user/projects/test/node_modules/@prisma/client/runtime/library.js:100:1478)
|  +309ms      at Object.start (/home/user/projects/test/node_modules/@prisma/client/runtime/library.js:101:2081)
|  +309ms      at Object.getDmmf (/home/user/projects/test/node_modules/@prisma/client/runtime/library.js:101:3489)
|  +309ms      at null.<anonymous> (/home/user/projects/test/node_modules/@prisma/client/runtime/library.js:174:2864)
|  +309ms      at null.<anonymous> (/home/user/projects/test/node_modules/@prisma/client/runtime/library.js:174:3268)
|  +309ms      at t._executeRequest (/home/user/projects/test/node_modules/@prisma/client/runtime/library.js:174:10726) {
|  +309ms    clientVersion: '4.11.0'
|  +309ms  }
|  Done in 318ms
```

**Comment by baryla** [comment]
Something that has fixed the `schema.prisma` not being found issue for me (at least locally - I haven't tested deploying it yet) was to bundle the external libraries all the time ie.

```diff
- external: app.local ? [] : ['@prisma/client', '.prisma']

+ external: ['@prisma/client', '.prisma']
```

Also, I discovered that if you specify the `output` path in your `schema.prisma` file and then try to import the types, client etc. in a separate module and then try to use that module in your apps, it'll break too with the `__filename` error. To go around this issue, remove the `output` path and inside the module that you'll import all over your apps, just export `@prisma/client`.

**Comment by jayair** [comment]
Would appreciate a sample repo if you get it working!

**Comment by geauser** [comment]
@jayair @baryla I managed to make prisma work locally as well but when I deploy it I get this error:
```
{
    "errorType": "Error",
    "errorMessage": "Cannot find package '@prisma/client' imported from /var/task/packages/functions/src/index.mjs\nDid you mean to import @prisma/client/index.js?",
    "code": "ERR_MODULE_NOT_FOUND",
    "stack": [
        "Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@prisma/client' imported from /var/task/packages/functions/src/index.mjs",
        "Did you mean to import @prisma/client/index.js?",
        "    at new NodeError (node:internal/errors:387:5)",
        "    at packageResolve (node:internal/modules/esm/resolve:852:9)",
        "    at moduleResolve (node:internal/modules/esm/resolve:901:20)",
        "    at defaultResolve (node:internal/modules/esm/resolve:1115:11)",
        "    at nextResolve (node:internal/modules/esm/loader:163:28)",
        "    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)",
        "    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)",
        "    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)",
        "    at link (node:internal/modules/esm/module_job:75:36)"
    ]
}
``` 

Also when looking at the source code of the lambda, the `package.json` is empty.  Any ideas?

**Comment by diegodev95** [comment]
@jayair i have the same problem with SST v2.10.4, i created graphql with pothos but in production generate this error 👎🏼 
```
{
    "errorType": "Error",
    "errorMessage": "Cannot find package '@prisma/client' imported from /var/task/packages/functions/src/graphql/graphql.mjs",
    "code": "ERR_MODULE_NOT_FOUND",
    "stack": [
        "Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@prisma/client' imported from /var/task/packages/functions/src/graphql/graphql.mjs",
        "    at new NodeError (node:internal/errors:387:5)",
        "    at packageResolve (node:internal/modules/esm/resolve:852:9)",
        "    at moduleResolve (node:internal/modules/esm/resolve:901:20)",
        "    at defaultResolve (node:internal/modules/esm/resolve:1115:11)",
        "    at nextResolve (node:internal/modules/esm/loader:163:28)",
        "    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)",
        "    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)",
        "    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)",
        "    at link (node:internal/modules/esm/module_job:75:36)"
    ]
}
```

**Comment by jayair** [comment]
I think somebody from the Prisma team put together an example and @revmischa is working on a new starter based on that. Join our Discord.

**Comment by thiagomorales** [comment]
Hi, i've managed to work by setting the runtime to `"nodejs18.x"` on latest sst version (2.19.1)
Using node runtime versions earlier than 18 and trying to import ESM modules will cause the `ERR_MODULE_NOT_FOUND` error.

**Comment by perfectbase** [comment]
I'm also having problems in making prisma work with sst. A minimal example would be much appreciated.
I would also love to have an example with prisma as a local shared package for use in multiple apps inside the monorepo.

**Comment by geauser** [comment]
@perfectbase I made a repo that I posted about on the SST discord but forgot to post it here, my bad.
Here it is: https://github.com/geauser/sst-prisma-example

You should join the discord as well most people ask questions over there!

**Comment by perfectbase** [comment]
@geauser thank you for the example project! it worked with npm. (for some reason it doesn't seem to work with pnpm, as the `.prisma/client` folder seems to be in a different place?)

I'm still trying to figure out how to make it work as a custom shared local package. ([turborepo with prisma](https://turbo.build/repo/docs/handbook/tools/prisma))

I'll try the discord server! thanks again!

**Comment by revmischa** [comment]
I'm waiting on a fix from prisma since recent versions refuse to find the schema.prisma file when used with SST

**Comment by azegarconnectauto** [comment]
@revmischa any update on that?

**Comment by revmischa** [comment]
They say there should be a fix in prisma 5.1, so I hope to revisit this soon

**Comment by a-eid** [comment]
@revmischa any updates on this, we have been struggling with prisma and sst for a while.

**Comment by revmischa** [comment]
> @revmischa any updates on this, we have been struggling with prisma and sst for a while.

Yeah sst-prisma is updated https://github.com/jetbridge/sst-prisma

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
