### ISSUE TITLE
adding sst to new astro project breaks build

### ISSUE THREAD

**Issue by lschierer** [sst/sst#2683]
I am trying to set up a new Astro.build project and to add SST to it.  before adding SST with the npx create-sst command, npm run build was working fine.  After running that command (and npm i -D) and accepting all defaults, I get the following error:

```
officium:EvonyTips_v2 luke$ npm run build

> @onwidget/astrowind@0.9.8 build
> astro build

02:20:09 PM [content] Unsupported file types found. Prefix with an underscore (`_`) to ignore:
- markdown-elements-demo-post.mdx
02:20:09 PM [content] Types generated 213ms
02:20:09 PM [build] output target: server
02:20:09 PM [build] deploy adapter: astro-sst/lambda
02:20:09 PM [build] Collecting build info...
02:20:09 PM [build] Completed in 230ms.
02:20:09 PM [build] Building server entrypoints...
[vite:import-glob] Invalid glob: "~/assets/images/**" (resolved: "~/assets/images/**"). It must start with '/' or './'
file: /Users/luke/src/astro/EvonyTips_v2/src/utils/images.ts
 error   Invalid glob: "~/assets/images/**" (resolved: "~/assets/images/**"). It must start with '/' or './'
  File:
    /Users/luke/src/astro/EvonyTips_v2/src/utils/images.ts
  Stacktrace:
Error: Invalid glob: "~/assets/images/**" (resolved: "~/assets/images/**"). It must start with '/' or './'
    at toAbsoluteGlob (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39733:11)
    at async Promise.all (index 0)
    at async file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39529:31
    at async Promise.all (index 0)
    at async parseImportGlob (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39543:13)
    at async transformGlobImport (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39563:21)
    at async Object.transform (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39370:28)
    at async transform (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/rollup/dist/es/shared/node-entry.js:23363:16)
    at async ModuleLoader.addModuleSource (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/rollup/dist/es/shared/node-entry.js:23569:30)

officium:EvonyTips_v2 luke$ 
```

and npm run dev gives a similar, but more verbose error:
```

  ✘ [ERROR] Invalid glob: "~/assets/images/**" (resolved: "~/assets/images/**"). It must start with '/' or './' [plugin vite:dep-scan]

    node_modules/vite/node_modules/esbuild/lib/main.js:1421:21:
      1421 │         let result = await callback({
           ╵                      ^

    at toAbsoluteGlob (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39733:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39529:31
    at async Promise.all (index 0)
    at async parseImportGlob (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39543:13)
    at async transformGlobImport (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39563:21)
    at async doTransformGlobImport (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:43618:24)
    at async file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:43856:35
    at async requestCallbacks.on-load (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1421:22)

  This error came from the "onLoad" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:43843:19)
    at handlePlugins (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:776:5)
    at /Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:2172:68
    at new Promise (<anonymous>)
    at Object.context (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:2172:27)
    at Object.context (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:2012:58)
    at prepareEsbuildScanner (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:43542:26)

  The plugin "vite:dep-scan" was triggered by this import

    <stdin>:15:7:
      15 │ import "/Users/luke/src/astro/EvonyTips_v2/src/utils/images.ts"
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


    at failureErrorWithLog (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:1057:54)
    at handleRequest (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/Users/luke/src/astro/EvonyTips_v2/node_modules/vite/node_modules/esbuild/lib/main.js:673:7)
02:18:50 PM [content] Unsupported file types found. Prefix with an underscore (`_`) to ignore:
- markdown-elements-demo-post.mdx
```

**Comment by lschierer** [comment]
I am unsure which side is responsible for this so I also filed it as [#152](https://github.com/onwidget/astrowind/issues/152) in the astro theme's issue tracker.

**Comment by fwang** [comment]
Hey Luke, if you just run `npx astro build`, do you get the same error?

Frank

--
<https://seed.run/>
Founder at SST <https://sst.dev>

SST <https://github.com/serverless-stack/serverless-stack> - OS framework
for building serverless apps
SEED <https://seed.run/> - Deploy, manage, and monitor serverless apps

**Comment by lschierer** [comment]
Yes, I do,
```
officium:EvonyTips_v2 luke$ npx astro build
02:49:56 PM [content] Unsupported file types found. Prefix with an underscore (`_`) to ignore:
- markdown-elements-demo-post.mdx
02:49:56 PM [content] Types generated 220ms
02:49:56 PM [build] output target: server
02:49:56 PM [build] deploy adapter: astro-sst/lambda
02:49:56 PM [build] Collecting build info...
02:49:56 PM [build] Completed in 239ms.
02:49:56 PM [build] Building server entrypoints...
[vite:import-glob] Invalid glob: "~/assets/images/**" (resolved: "~/assets/images/**"). It must start with '/' or './'
file: /Users/luke/src/astro/EvonyTips_v2/src/utils/images.ts
 error   Invalid glob: "~/assets/images/**" (resolved: "~/assets/images/**"). It must start with '/' or './'
  File:
    /Users/luke/src/astro/EvonyTips_v2/src/utils/images.ts
  Stacktrace:
Error: Invalid glob: "~/assets/images/**" (resolved: "~/assets/images/**"). It must start with '/' or './'
    at toAbsoluteGlob (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39733:11)
    at async Promise.all (index 0)
    at async file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39529:31
    at async Promise.all (index 0)
    at async parseImportGlob (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39543:13)
    at async transformGlobImport (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39563:21)
    at async Object.transform (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:39370:28)
    at async transform (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/rollup/dist/es/shared/node-entry.js:23363:16)
    at async ModuleLoader.addModuleSource (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/rollup/dist/es/shared/node-entry.js:23569:30)

officium:EvonyTips_v2 luke$ 
```

**Comment by fwang** [comment]
I see. Likely an issue with Astro.

I don't know Astro.. sorry I can't be of more help. Maybe look into where
that `~/assets/images/**` path comes from?

Frank

--
<https://seed.run/>
Founder at SST <https://sst.dev>

SST <https://github.com/serverless-stack/serverless-stack> - OS framework
for building serverless apps
SEED <https://seed.run/> - Deploy, manage, and monitor serverless apps

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
