### ISSUE TITLE
Trace: TypeError: Cannot read properties of undefined (reading 'runtime')

### ISSUE THREAD

**Issue by pruales** [sst/sst#2732]
I'm getting the following error randomly when my cron job is invoked:

```
Error: Cannot read properties of undefined (reading 'runtime')

Trace: TypeError: Cannot read properties of undefined (reading 'runtime')
    at Object.cb (file:///Users/paul/src/podcastGPT/node_modules/sst/runtime/workers.js:33:44)
    at Object.publish (file:///Users/paul/src/podcastGPT/node_modules/sst/bus.js:28:21)
    at DeviceClient.<anonymous> (file:///Users/paul/src/podcastGPT/node_modules/sst/iot.js:140:17)
    at DeviceClient.emit (node:events:513:28)
    at DeviceClient.emit (node:domain:489:12)
    at MqttClient.<anonymous> (/Users/paul/src/podcastGPT/node_modules/aws-iot-device-sdk/device/index.js:826:12)
    at MqttClient.emit (node:events:513:28)
    at MqttClient.emit (node:domain:489:12)
    at Arguments.<anonymous> (/Users/paul/src/podcastGPT/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:1265:27)
    at MqttClient.options.customHandleAcks (/Users/paul/src/podcastGPT/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:183:150)
    at process.<anonymous> (file:///Users/paul/src/podcastGPT/node_modules/sst/cli/sst.js:56:17)
    at process.emit (node:events:525:35)
    at process.processEmit [as emit] (/Users/paul/src/podcastGPT/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (node:internal/process/execution:149:25)
    at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32
```

My stack is setup like this:

```typescript
import { Cron, StackContext, Table } from "sst/constructs";

export function PodcastGPTStack({ stack }: StackContext) {
  const table = new Table(stack, "Podcasts", {
    fields: {
      id: "string",
      title: "string",
      enclosure: "string",
      isoDate: "string",
    },
    primaryIndex: { partitionKey: "id", sortKey: "isoDate" },
  });

  const cron = new Cron(stack, "Cron", {
    schedule: "rate(1 minute)",
    job: "packages/functions/src/lambda.main",
  });
  cron.bind([table]);
}

``` 

Edit: Here's a more complete example showing the first invocation worked but then the second one invokes `undefined` and crashes:
```
✔  Deployed:
   PodcastGPTStack

|  Invoked packages/functions/src/lambda.main
|  +933ms  (node:29769) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
|  +933ms  
|  +933ms  Please migrate your code to use AWS SDK for JavaScript (v3).
|  +933ms  For more information, check the migration guide at https://a.co/7PzMCcy
|  +933ms  (Use `node --trace-warnings ...` to show where the warning was created)
|  +3054ms 137
|  +3060ms 137
|  Done in 3270ms
|  Invoked undefined
Error: Cannot read properties of undefined (reading 'runtime')

Trace: TypeError: Cannot read properties of undefined (reading 'runtime')
    at Object.cb (file:///Users/paul/src/podcastGPT/node_modules/sst/runtime/workers.js:33:44)
    at Object.publish (file:///Users/paul/src/podcastGPT/node_modules/sst/bus.js:28:21)
    at DeviceClient.<anonymous> (file:///Users/paul/src/podcastGPT/node_modules/sst/iot.js:140:17)
    at DeviceClient.emit (node:events:513:28)
    at DeviceClient.emit (node:domain:489:12)
    at MqttClient.<anonymous> (/Users/paul/src/podcastGPT/node_modules/aws-iot-device-sdk/device/index.js:826:12)
    at MqttClient.emit (node:events:513:28)
    at MqttClient.emit (node:domain:489:12)
    at Arguments.<anonymous> (/Users/paul/src/podcastGPT/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:1265:27)
    at MqttClient.options.customHandleAcks (/Users/paul/src/podcastGPT/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:183:150)
    at process.<anonymous> (file:///Users/paul/src/podcastGPT/node_modules/sst/cli/sst.js:56:17)
    at process.emit (node:events:525:35)
    at process.processEmit [as emit] (/Users/paul/src/podcastGPT/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (node:internal/process/execution:149:25)
    at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

**Comment by Grant-Keiter-FHR** [comment]
I am seeing this error when a lambda is triggered from an SQS queue.

**Comment by jayair** [comment]
Can you post this on #help on Discord?

**Comment by fwang** [comment]
@pruales @Grant-Keiter-FHR do u recall if u renamed the Cron/Queue in your stacks code prior to this happening?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
