### ISSUE TITLE
`sst dev` crashes on unhandled promise rejections

### ISSUE THREAD

**Issue by estyrke** [sst/sst#2869]
I have a `Function` that I call by manually invoking it from the console. I accidentally missed an `await` when calling an async function, and if that function then happens to throw an error, the whole `sst dev` process will die.

```

|  Invoked packages/functions/src/scripts/import-db.handler
|  +838ms  Importing users...
Error: Invariant failed

Trace: Error: Invariant failed
    at invariant (/Users/emilst/Code/lkss/internwebb/node_modules/.pnpm/tiny-invariant@1.3.1/node_modules/tiny-invariant/dist/esm/tiny-invariant.js:12:11)
    at importEvents (/Users/emilst/Code/lkss/internwebb/packages/functions/src/scripts/import-db.ts:320:3)
    at handler (/Users/emilst/Code/lkss/internwebb/packages/functions/src/scripts/import-db.ts:375:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/emilst/Code/lkss/internwebb/node_modules/.pnpm/sst@2.8.6/node_modules/sst/support/nodejs-runtime/index.mjs:131:16
    at process.<anonymous> (file:///Users/emilst/Code/lkss/internwebb/node_modules/.pnpm/sst@2.8.6/node_modules/sst/cli/sst.js:58:17)
    at process.emit (node:events:525:35)
    at process.processEmit [as emit] (/Users/emilst/Code/lkss/internwebb/node_modules/.pnpm/signal-exit@3.0.7/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (node:internal/process/execution:149:25)

Need help with this error? Join the SST community on Discord https://sst.dev/discord
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by jayair** [comment]
Oh good catch.

**Comment by thdxr** [comment]
yes i've seen this! thank you for figuring out what it is let me see if I can handle it

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
