### ISSUE TITLE
AstroJS with dynamic routing issues with SST

### ISSUE THREAD

**Issue by anselm94** [sst/sst#2970]
Hello, This is a _Bug Report_.

I tried deploying an Astro site with dynamic routes and everything went through without any problem. However, accessing the site led to `Internal Server Error`.

On closer look, I observed below problem:
```
<time>	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "TypeError",
    "errorMessage": "(0 , import_path_to_regexp.compile) is not a function",
    "stack": [
        "TypeError: (0 , import_path_to_regexp.compile) is not a function",
        "    at getRouteGenerator (file:///var/task/packages/web-2/dist/server/entry.mjs:2150:52)",
        "    at deserializeRouteData (file:///var/task/packages/web-2/dist/server/entry.mjs:2160:15)",
        "    at deserializeManifest (file:///var/task/packages/web-2/dist/server/entry.mjs:2171:18)",
        "    at file:///var/task/packages/web-2/dist/server/entry.mjs:137262:31",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"
    ]
}
```

Running `npm list path-to-regexp` returned below
```
├─┬ sst@2.12.0
│ └─┬ express@4.18.2
│   └── path-to-regexp@0.1.7
└─┬ web-2@0.0.1 -> ./packages/web-2
  └─┬ astro@2.6.2
    └── path-to-regexp@6.2.1
```

Adding below to the root `package.json` fixed the issue
```jsonc
...
  "overrides": {
    "path-to-regexp": "^6.2.1"
  },
...
```

---

## Versions

Node: `v16.19.1`
SST: `2.12.0`
Astro: `2.6.2`

**Comment by jayair** [comment]
Hmm that's odd.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
