### ISSUE TITLE
An exception thrown in a stack doesn't surface properly in dev mode

### ISSUE THREAD

**Issue by berenddeboer** [sst/sst#3005]
I got this about with `sst dev`:

```
 Checking for changes
Error: Cannot read properties of undefined (reading 'split')

Trace: TypeError: Cannot read properties of undefined (reading 'split')
    at build (file:///Users/bdeboer/src/node_modules/sst/cli/commands/dev.js:167:22)
    at async file:///Users/bdeboer/src/node_modules/sst/cli/commands/dev.js:238:9
    at async Promise.all (index 9)
```

The reason is not made clear, but is visible if you do a build:

```
Executing command: sst build --to ../../dist/packages/sst-rds
Error: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "No vpc defined for account 257611358457".
```

That exception is thrown by me. It would be nice if this would have surfaced in dev properly as well.

**Comment by jayair** [comment]
Sorry again but on #help would be better.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
