### ISSUE TITLE
ISR failing on new NextJS project

### ISSUE THREAD

**Issue by Jose4gg** [sst/sst#3075]
If I have a  app router page with 

```typescript
export const revalidate = n > 1;

// OR

export const revalidate = false;
```

The server returns `500: Internal Server Error`, the error on cloudwatch is the next one:

```
2023-07-03T16:41:46.340Z	2a49107e-c3ed-4042-8a97-506461b6a567	ERROR	{
  clientName: 'S3Client',
  commandName: 'ListObjectsV2Command',
  input: {
    Bucket: '...handler-site-sites3bucket2b...',
    Prefix: '_cache/JvFBE1QrJwpgwvgqoGIko/favicon.ico'
  },
  error: Ma [CredentialsProviderError]: Could not load credentials from any providers
      at /var/task/cache.cjs:29:7021
      at /var/task/cache.cjs:1:27135
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async i (/var/task/cache.cjs:1:27479)
      at async xC.credentialProvider (/var/task/cache.cjs:1:27628)
      at async xC.signRequest (/var/task/cache.cjs:2:848)
      at async /var/task/cache.cjs:12:4945
      at async /var/task/cache.cjs:13:25781
      at async /var/task/cache.cjs:1:20115
      at async Uh.getIncrementalCache (/var/task/cache.cjs:33:192758) {
    tryNextLink: false,
    '$metadata': { attempts: 1, totalRetryDelay: 0 }
  },
  metadata: { attempts: 1, totalRetryDelay: 0 }
}

```

**Comment by jayair** [comment]
Replying on Discord.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
