### ISSUE TITLE
Next.js: `sst bind` causes webpack error when `middleware.ts` is present

### ISSUE THREAD

**Issue by relsunkaev** [sst/sst#3104]
## Issue
As in the title. This error comes up when navigating to any page.

## Stack Trace
```
Error [EvalError]: Code generation from strings disallowed for this context
    at <unknown> (file:///.../.next/server/src/middleware.js:19)
    at (middleware)/../../node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=%2F...%2Fmiddleware.ts&page=%2Fsrc%2Fmiddleware&rootDir=...&matchers=&preferredRegion=&middlewareConfig=e30%3D! (file:///.../.next/server/src/middleware.js:19:1)
    at __webpack_require__ (file:///.../.next/server/edge-runtime-webpack.js:37:33)
    at __webpack_exec__ (file:///.../.next/server/src/middleware.js:1499:48)
    at <unknown> (file:///.../.next/server/src/middleware.js:1500:37)
    at webpackJsonpCallback (file:///.../.next/server/edge-runtime-webpack.js:1128:39)
    at <unknown> (file:///.../.next/server/src/middleware.js:10:61)
    at Script.runInContext (node:vm:141:12)
    at runInContext (node:vm:291:6)
    at evaluateInContext (file:///.../node_modules/next/dist/server/web/sandbox/context.js:357:38)
    at getRuntimeContext (file:///.../node_modules/next/dist/server/web/sandbox/sandbox.js:69:9) {
  digest: undefined
}
```

If an `instrumentation.ts` file is also present with an empty (or non-empty) `register` function, the error changes to

```
Error [EvalError]: Code generation from strings disallowed for this context
    at <unknown> (file:///.../.next/server/edge-instrumentation.js:19)
    at ./src/instrumentation.ts (file:///.../.next/server/edge-instrumentation.js:19:1)
    at __webpack_require__ (file:///.../.next/server/edge-runtime-webpack.js:37:33)
    at __webpack_exec__ (file:///.../.next/server/edge-instrumentation.js:25:48)
    at <unknown> (file:///.../.next/server/edge-instrumentation.js:26:37)
    at webpackJsonpCallback (file:///.../.next/server/edge-runtime-webpack.js:1128:39)
    at Array.forEach (<anonymous>)
    at <unknown> (file:///.../.next/server/edge-runtime-webpack.js:1142:31)
    at <unknown> (file:///.../.next/server/edge-runtime-webpack.js:1144:13)
    at <unknown> (file:///.../.next/server/edge-runtime-webpack.js:1150:12)
    at Script.runInContext (node:vm:141:12) {
  digest: undefined
}
```

## Dependencies

| Package           | Version |
| ----------------- | ------- |
| sst        | 2.19.0  |
| next           | 13.4.8    |
| node        | 18.16.1    |

**Comment by jayair** [comment]
Hmm can you post this on #open-next on Discord?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
