### ISSUE TITLE
region not set correctly when use a cross-account role profile

### ISSUE THREAD

**Issue by StrikeDing** [sst/sst#3223]
I am trying to use a cross-account role to develope my application, there is my profile in .aws/config:
```
[profile A-role]
region = cn-north-1
output = json
credential_process = "aws_signing_helper.exe" credential-process --certificate ****.pem --private-key ****.pem --region cn-north-1 --trust-anchor-arn ******* --profile-arn ******* --role-arn ****** --with-proxy

[profile B-role]
region = cn-north-1
role_arn = ******
source_profile = A-role
role_session_name = roleTD
```
The profile worked fine in the aws cli, I can assumed to B-role with`--profile B-role` option.
Then I use the profile in sst to deploy my application,  I specify it in `sst.config.ts`:
```typesciprt
  config(_input) {
    return {
      ....
      region: "cn-north-1",
      profile: "B-role",
      ....
    };
  },
```
------------------------------------------------------------------------------------------------------

And then the problem occurred, the error show below:
```
Error: The security token included in the request is invalid
Trace: InvalidClientTokenId: The security token included in the request is invalid
    at throwDefaultError (D:\codebase\cert-manager-backend\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:8:22)
    at D:\****\****\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:18:39
    at de_AssumeRoleCommandError (D:\****\****\node_modules\@aws-sdk\client-sts\dist-cjs\protocols\Aws_query.js:132:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\****\****\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
    at async D:\****\****\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:14:20
    at async D:\****\****\node_modules\@smithy\middleware-retry\dist-cjs\retryMiddleware.js:27:46
    at async D:\****\****\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26
    at async Object.roleAssumer (D:\****\****\node_modules\@aws-sdk\client-sts\dist-cjs\defaultStsRoleAssumers.js:35:33)
	...
```
so I checked the [defaultStsRoleAssumers.ts](https://github.com/aws/aws-sdk-js-v3/blob/acaaadf33edbe6fea44d9f322ac8049c464985d5/clients/client-sts/src/defaultStsRoleAssumers.ts#L55C9-L55C68)
```
...
const getDefaultRoleAssumer = (stsOptions, stsClientCtor) => {
    let stsClient;
    let closureSourceCreds;
    return async (sourceCreds, params) => {
        closureSourceCreds = sourceCreds;
        if (!stsClient) {
            const { logger, region, requestHandler } = stsOptions;
            stsClient = new stsClientCtor({
                logger,
                credentialDefaultProvider: () => async () => closureSourceCreds,
                region: decorateDefaultRegion(region || stsOptions.region),
                ...(requestHandler ? { requestHandler } : {}),
            });
...
```

`region: decorateDefaultRegion(region || stsOptions.region)`

--->I found that the region is set to `us-east-1`, but what I set in the ` sst.config.ts` and `.aws/config`  is 'cn-north-1'.

------------------------------------------------------------------------------------------------------

I don't know if I missed anything about the config of region, could sst team please help to check this issue?

enviroment:
```
"@aws-sdk/client-sts": "3.382.0"
"sst": "^2.22.6"
"aws-cdk-lib": "2.84.0"
```
---

If you've already posted your issue on Discord, make sure to leave a link to it here.

**Comment by StrikeDing** [comment]
I add  a parameter `clientConfig: {region: project.config.region}` when create `fromNodeProviderChain` in [sst/packages/sst/src/credentials.ts](https://github.com/sst/sst/blob/8f205d5993820ddc3ac1fb9206881b703221ae7d/packages/sst/src/credentials.ts#L20) and it work fine.
after change:
```
export const useAWSCredentialsProvider = Context.memo(() => {
    const project = useProject();
    Logger.debug("Using AWS profile", project.config.profile);
    const provider = fromNodeProviderChain({
        clientConfig: {region: project.config.region},   //add a parameter at here
        profile: project.config.profile,
        roleArn: project.config.role,
        mfaCodeProvider: async (serialArn) => {
            const readline = await import("readline");
            const rl = readline.createInterface({
                input: process.stdin,
                output: process.stdout,
            });
            return new Promise((resolve) => {
                Logger.debug(`Require MFA token for serial ARN ${serialArn}`);
                const prompt = () => rl.question(`Enter MFA code for ${serialArn}: `, async (input) => {
                    if (input.trim() !== "") {
                        resolve(input.trim());
                        rl.close();
                    }
                    else {
                        // prompt again if no input
                        prompt();
                    }
                });
                prompt();
            });
        },
    });
    return provider;
});
```

**Comment by fwang** [comment]
Thanks @StrikeDing!

It's in v2.24.6
