### ISSUE TITLE
cannot even start a next.js project - user/amplify-dev is not authorized to perform: iot:DescribeEndpoint 

### ISSUE THREAD

**Issue by zurcacielos** [sst/sst#3278]
First experience running SST for the first time.

> sst bind next dev

Please enter a name you’d like to use for your personal stage. Or hit enter to use fabia: 
Attention: SST now collects completely anonymous telemetry regarding usage. This is used to guide SST's roadmap.
You can learn more, including how to opt-out of this anonymous program, by heading over to:
https://docs.sst.dev/anonymous-telemetry

(node:22496) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

Error: User: arn:aws:iam::137541761544:user/amplify-dev is not authorized to perform: iot:DescribeEndpoint because no identity-based policy allows the iot:DescribeEndpoint action

Trace: AccessDeniedException: User: arn:aws:iam::137541761544:user/amplify-dev is not authorized to perform: iot:DescribeEndpoint because no identity-based policy allows the iot:DescribeEndpoint action
    at throwDefaultError (C:\git\next\pime\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:8:22)
    at C:\git\next\pime\node_modules\@smithy\smithy-client\dist-cjs\default-error-handler.js:18:39
    at de_DescribeEndpointCommandError (C:\git\next\pime\node_modules\@aws-sdk\client-iot\dist-cjs\protocols\Aws_restJson1.js:9968:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\git\next\pime\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
    at async C:\git\next\pime\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:14:20
    at async StandardRetryStrategy.retry (C:\git\next\pime\node_modules\@aws-sdk\middleware-retry\node_modules\@smithy\middleware-retry\dist-cjs\StandardRetryStrategy.js:51:46)
    at async C:\git\next\pime\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26
    at async file:///C:/git/next/pime/node_modules/sst/iot.js:8:22
    at async file:///C:/git/next/pime/node_modules/sst/iot.js:24:22
    at async Object.handler (file:///C:/git/next/pime/node_modules/sst/cli/commands/bind.js:45:9)
    at process.<anonymous> (file:///C:/git/next/pime/node_modules/sst/cli/sst.js:62:21)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at process._fatalException (node:internal/process/execution:149:25)
    at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Need help with this error? Post it in #help on the SST Discord https://sst.dev/discord

Process finished with exit code 1

**Comment by jayair** [comment]
Can you post this on #help in Discord? It looks like your credentials aren't configured correctly?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
