### ISSUE TITLE
graphql-dynamo example does not work. 

### ISSUE THREAD

**Issue by lschierer** [sst/sst#3279]
The example for using graphql with dyamodb and electrodb in https://github.com/serverless-stack/sst.git's examples directory doesn't work.  I ran ```pnpm i``` followed by ```pnpm run build``` and get the following errors:

```
Building static site packages/web

> web@0.0.0 build
> tsc && vite build

../graphql/urql.ts:10:3 - error TS2305: Module '"urql"' has no exported member 'defaultExchanges'.

10   defaultExchanges,
     ~~~~~~~~~~~~~~~~

../graphql/urql.ts:17:3 - error TS2305: Module '"./genql"' has no exported member 'QueryRequest'.

17   QueryRequest,
     ~~~~~~~~~~~~

../graphql/urql.ts:19:3 - error TS2724: '"./genql"' has no exported member named 'MutationRequest'. Did you mean 'MutationResult'?

19   MutationRequest,
     ~~~~~~~~~~~~~~~


Found 3 errors in the same file, starting at: ../graphql/urql.ts:10

npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: web@0.0.0 
npm ERR!   at location: /Users/luke/src/sst/examples/graphql-dynamo/packages/web 
Error: There was a problem building the "site" StaticSite.

Trace: Error: There was a problem building the "site" StaticSite.
    at StaticSite.buildApp (file:///Users/luke/src/sst/examples/graphql-dynamo/node_modules/.pnpm/sst@2.24.11_@types+react@18.2.20/node_modules/sst/constructs/StaticSite.js:202:23)
    at file:///Users/luke/src/sst/examples/graphql-dynamo/node_modules/.pnpm/sst@2.24.11_@types+react@18.2.20/node_modules/sst/constructs/StaticSite.js:68:18
    at runTask (file:///Users/luke/src/sst/examples/graphql-dynamo/node_modules/.pnpm/sst@2.24.11_@types+react@18.2.20/node_modules/sst/constructs/deferred_task.js:29:21)
    at file:///Users/luke/src/sst/examples/graphql-dynamo/node_modules/.pnpm/sst@2.24.11_@types+react@18.2.20/node_modules/sst/constructs/deferred_task.js:40:21
    at new Promise (<anonymous>)
    at Object.run (file:///Users/luke/src/sst/examples/graphql-dynamo/node_modules/.pnpm/sst@2.24.11_@types+react@18.2.20/node_modules/sst/constructs/deferred_task.js:17:20)
    at App.finish (file:///Users/luke/src/sst/examples/graphql-dynamo/node_modules/.pnpm/sst@2.24.11_@types+react@18.2.20/node_modules/sst/constructs/App.js:189:34)
    at Module.synth (file:///Users/luke/src/sst/examples/graphql-dynamo/node_modules/.pnpm/sst@2.24.11_@types+react@18.2.20/node_modules/sst/stacks/synth.js:64:19)
    at async Object.handler (file:///Users/luke/src/sst/examples/graphql-dynamo/node_modules/.pnpm/sst@2.24.11_@types+react@18.2.20/node_modules/sst/cli/commands/build.js:11:20)
    at process.<anonymous> (file:///Users/luke/src/sst/examples/graphql-dynamo/node_modules/.pnpm/sst@2.24.11_@types+react@18.2.20/node_modules/sst/cli/sst.js:60:17)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at process._fatalException (node:internal/process/execution:149:25)
    at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

**Comment by lschierer** [comment]
While I try hard not to criticize an open source project, it would really help if you all could work on some consistency across your documentation.  
* https://docs.sst.dev/learn/initialize-the-database uses graphql to read from RDS
* https://sst.dev/guide.html uses dynamodb without either ElectroDB or graphql
* https://docs.sst.dev/databases#using-a-client talks about ElectroDB 
* none of 
   * https://sst.dev/examples/how-to-create-a-rest-api-with-serverless.html

**Comment by jayair** [comment]
I just put up a sign recently on that tutorial that it needs an update. It's on my todo to go through that and fix it. It looks like there was a genql or urql update recently.

**Comment by lschierer** [comment]
it looks like there is substantial overlap between this example and the create-sst-dynamo example? As a feature request, it would be awesome if one or both of these could be explained in detail on the website the way a few of the others are to help those of us newer to things like graphql and electrodb understand what the example is doing.

**Comment by jayair** [comment]
Yeah when I work through this we'll figure out what we want to do here. I think the mistake we made before was trying to have a couple of different versions.

**Comment by kmerri11** [comment]
Is there an update for this request? Perhaps a workaround to make the example work? Thank you.

**Comment by jayair** [comment]
I did take a pass at it but I think I need to do a proper update. Sorry!

But if you are having specific issues, post it over on #help on Discord?

**Comment by kmerri11** [comment]
Here's how I removed build errors. Please correct me if it's the wrong approach. In `graphql/urql.ts`:

Remove `defaultExchanges` from imports:
```
import {
  useQuery,
  useClient,
  createClient,
  createRequest,
  RequestPolicy,
  OperationResult,
  UseMutationState,
  OperationContext,
  //defaultExchanges,
  UseMutationResponse,
} from "urql";
```

Replace `QueryRequest` with `QueryGenqlSelection` and `MutationRequest` with `MutationGenqlSelection`:
```
import {
  QueryResult,
  // QueryRequest,
  QueryGenqlSelection, // append
  MutationResult,
  MutationGenqlSelection, // append
  //MutationRequest,
  generateQueryOp,
  generateMutationOp,
} from "./genql";
```

In the `useTypedQuery` function, replace `QueryRequest` to `QueryGenqlSelection`:
```useTypedQuery<Query extends QueryRequest>```

In the `useTypedMutation` function, replace `MutationRequest` with `MutationGenqlSelection`:
```Mutation extends MutationGenqlSelection```

**Comment by jayair** [comment]
That roughly looks right to me. I'll need to try it out though!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
