### ISSUE TITLE
Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by ignaciolarranaga** [sst/sst#3288]
Guys some idea how I can see what is this?

It is on a server side rendering page with the pages router, all that I have is this appearing in the server lambda edge log:
```
2023-06-14T18:34:51.873Z	b0f8d4d1-5316-4e1d-9661-b79aa790c32e	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of undefined (reading 'value')",
    "stack": [
        "TypeError: Cannot read properties of undefined (reading 'value')",
        "    at Gt (/var/task/LambdaOriginRequest.js:12:3176)",
        "    at Bt (/var/task/LambdaOriginRequest.js:12:2335)",
        "    at Runtime.no [as handler] (/var/task/LambdaOriginRequest.js:12:2282)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1086:29)"
    ]
}
```

**Comment by jayair** [comment]
Post in #help on our Discord with more details?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
