### ISSUE TITLE
SSR warmer invoke errors

### ISSUE THREAD

**Issue by bayssmekanique** [sst/sst#3364]
The SSR warmer is throwing `Invoke Error` in the logs when run against Astro site. Not certain if this is an Astro specific issue or a general issue.

**INFO**
```
2023-10-02T15:42:55.339Z	99e5e56a-ab54-4b83-83b1-f1b245da5495	INFO	{
  event: 'warmer invoked',
  functionName: 'astro-personal-website-Si-astrositeServerFunction4-t3VphKEUPtNn',
  concurrency: 1,
  warmerId: 'warmer-s3of1l'
}
```

**ERROR**
```
2023-10-02T15:42:56.599Z	99e5e56a-ab54-4b83-83b1-f1b245da5495	ERROR	Invoke Error 	
{
    "errorType": "SyntaxError",
    "errorMessage": "Unexpected end of JSON input",
    "stack": [
        "SyntaxError: Unexpected end of JSON input",
        "    at JSON.parse (<anonymous>)",
        "    at file:///var/task/index.mjs:34203:26",
        "    at Array.forEach (<anonymous>)",
        "    at Runtime.handler (file:///var/task/index.mjs:34198:7)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    ]
}
```

Also, warmer function default configuration has too much memory allocated. Most runs are using less than 90MB of member, so function memory should be reduced to `125MB` (or less?).

---

Issue originally noted in [Discord Astro Channel](https://discord.com/channels/983865673656705025/1068236979659092038/1153356345379147959)

**Comment by bayssmekanique** [comment]
Error seems to be originating from this line: https://github.com/sst/sst/blob/347666100a43047512b614fb785bedd61e4a911f/packages/sst/support/ssr-warmer/index.ts#L67
