### ISSUE TITLE
`sst bind` fails on stacks containing a Service with bound constructs

### ISSUE THREAD

**Issue by zvictor** [sst/sst#3451]
_Discord discussion: https://discord.com/channels/983865673656705025/1166372275185000598_

---

## Description:

When running the `sst bind` command on a stack that contains a `Service` with constructs bound through the `service.bind` call, a TypeError is thrown: `Cannot read properties of null (reading 'addEnvironment')`. This error seems to occur because `this.container` is `null` when running locally.

```haskell
Error: Cannot read properties of null (reading 'addEnvironment')

Trace: TypeError: Cannot read properties of null (reading 'addEnvironment')
    at Service.addEnvironmentForService (file:///node_modules/.pnpm/sst@2.32.1_@types+react@18.2.16/node_modules/sst/constructs/Service.js:567:24)
    at file:///node_modules/.pnpm/sst@2.32.1_@types+react@18.2.16/node_modules/sst/constructs/Service.js:554:64
    at Array.forEach (<anonymous>)
    at file:///node_modules/.pnpm/sst@2.32.1_@types+react@18.2.16/node_modules/sst/constructs/Service.js:554:33
    at Array.forEach (<anonymous>)
    at Service.bindForService (file:///node_modules/.pnpm/sst@2.32.1_@types+react@18.2.16/node_modules/sst/constructs/Service.js:551:47)
    at Service.bind (file:///node_modules/.pnpm/sst@2.32.1_@types+react@18.2.16/node_modules/sst/constructs/Service.js:323:14)
    at EmptyStack.WhatsappListenerStack (file:///deployment/.sst.config.1698353557905.mjs:599:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.stacks [as fn] (file:///deployment/.sst.config.1698353557905.mjs:630:5)
    at async synthInRoot (file:///node_modules/.pnpm/sst@2.32.1_@types+react@18.2.16/node_modules/sst/stacks/synth.js:56:13)
    at async Module.synth (file:///node_modules/.pnpm/sst@2.32.1_@types+react@18.2.16/node_modules/sst/stacks/synth.js:19:16)
    at async buildApp (file:///node_modules/.pnpm/sst@2.32.1_@types+react@18.2.16/node_modules/sst/cli/commands/bind.js:84:13)
    at async Object.handler (file:///node_modules/.pnpm/sst@2.32.1_@types+react@18.2.16/node_modules/sst/cli/commands/bind.js:51:9)
```

## Steps to reproduce:

1. Create a stack with a `Service`.
1. Bind constructs to the `Service` using the `service.bind` call (do not set it in the constructor).
1. Run the `sst bind` command on the stack.

## Expected result:

The `sst bind` command should successfully bind the constructs to the Service.

## Actual result:

The `sst bind` command throws a `TypeError: Cannot read properties of null (reading 'addEnvironment')`.

## Additional information:

The error does not occur if the binds are defined in the Service itself. It only happens if `service.bind` is called separately. The error also appears when running `sst remove`.

A potential workaround involves checking if `this.doNotDeploy` is true before calling this.container.addEnvironment(name, value) and attachPermissionsToRole(this.taskDefinition.taskRole, permissions):

```js
 addEnvironmentForService(name, value) {
    if (!this.doNotDeploy){
        this.container.addEnvironment(name, value);
    }
}
attachPermissionsForService(permissions) {
    if (!this.doNotDeploy){
        attachPermissionsToRole(this.taskDefinition.taskRole, permissions);
    }
}
```

The issue could be related to the `app.mode` being set as remove during `sst bind`. Further investigation is required to determine the root cause and find a proper solution.

---

_Discord discussion: https://discord.com/channels/983865673656705025/1166372275185000598_

**Comment by fwang** [comment]
Fixed - https://github.com/sst/sst/commit/8b802f118a78a296d43b229811e26ae60e13f616

Will be in the next release.
