### ISSUE TITLE
How to change region to ca-central-1?

### ISSUE THREAD

**Issue by jansdhillon** [sst/sst#3491]
Hello,

I am very excited to start using this package but I'm a bit confused about how to change my region. I have my AWS credentials configured to be ca-central-1 but when I run`npx create-sst@latest` it auto-sets my region to us-east-1. Everything seems to go great but when I change the region to ca-central-1, everything breaks. 

I am just using the code from the NextJs example but even that gives me this error:
```
 ⨯ Error: Cannot use Bucket.public. Please make sure it is bound to this function.
    at Object.get (file:///Users/imigh/Coding/COSC499/year-long-project-team-9/app/front-end/node_modules/sst/node/util/index.js:32:27)
    at getServerSideProps (webpack-internal:///./src/pages/MyRequests.tsx:29:69)
    at /Users/imigh/Coding/COSC499/year-long-project-team-9/app/front-end/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:47:250
    at /Users/imigh/Coding/COSC499/year-long-project-team-9/app/front-end/node_modules/next/dist/server/lib/trace/tracer.js:117:36
 ```
 
I was getting this error earlier but it seems to have gone away... until now. I deployed my app on us-east-1 fine but when I run the same command for ca-central-1, I get this:

```
|  Site LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a AWS::Lambda::Function CREATE_FAILED Resource handler returned message: "Uploaded file must be a non-empty zip (Service: Lambda, Status Code: 400, Request ID: 6b3bcec8-f122-4a06-8b8e-8ce2fcb4edb7)" (RequestToken: bd4f24a2-674a-a639-7e17-c64c16dd2751, HandlerErrorCode: InvalidRequest)
|  Site site/ServerFunction/AssetReplacer Custom::AssetReplacer CREATE_FAILED Resource creation cancelled
|  Site site/ImageFunction/ServiceRole/DefaultPolicy AWS::IAM::Policy CREATE_FAILED Resource creation cancelled
|  Site site/S3UploaderPolicy AWS::IAM::Policy CREATE_FAILED Resource creation cancelled
|  Site site/RevalidationFunction AWS::Lambda::Function CREATE_FAILED Resource creation cancelled
```

Just to confirm, it is possible to change my region right? I'm not sure if it'd be the end of the world if the bucket is in the US, but my AWS account is part of my (Canadian) university cloud organization so I'm not really sure if that'd become an issue. 

Any help or guidance is appreciated... I was going to start wiping everything but I feel like I'm just missing something.

---

**Comment by jansdhillon** [comment]
I was able to get it working with my bucket and site deployed and working by just wiping everything SST-related and starting fresh with ca-central-1. If you are doing this just make sure you delete your SST Bootstrap Stack and the CDKToolkit from CloudFormation, that's what I got stuck on. After that just try creating the SST app again.
