### ISSUE TITLE
Certificate Requestor still failing in Node v18

### ISSUE THREAD

**Issue by bayssmekanique** [sst/sst#3536]
This issue was originally noted in PR #3519 and fix was merged, but the issue appears to still exist in the current `master` branch.

The Customer Resource function is failing with this error:
```
2023-11-27T00:04:33.404Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

There appears to be both the `index.js` and `index.mjs` files uploaded into the runtime, and given that the error is for finding the module `aws-sdk`, I'm assuming this means the `index.js` file is being prioritized over the `index.mjs` file.

**Comment by bayssmekanique** [comment]
Nevermind. The ultimate issue was that the `certificate-requestor` directory in the `dist` had the old `index.js` file still in it from before the rename. Nuked the `sst/dist` then rebuilt and everything works fine now 😅. FWIW, it does seem like there should be some sort of directory clear before the build process.
