### ISSUE TITLE
AWS Secrets Manager: ValidationException: Invalid namedev and prod deployments differences.  

### ISSUE THREAD

**Issue by belarusrulez** [sst/sst#3795]
Hello everyone 🙂 I am trying to do npx sst build --stage prod or npx sst deploy --stage prod and getting 
   ```
Collecting page data  ...Error retrieving secret from AWS Secrets Manager: ValidationException: Invalid name. Must be a valid name containing alphanumeric characters, or any of the following: -/_+=.@!
Error retrieving secret from AWS Secrets Manager: ValidationException: Invalid name. Must be a valid name containing alphanumeric characters, or any of the following: -/_+=.@!
ValidationException: Invalid name. Must be a valid name containing alphanumeric characters, or any of the following: -/_+=.@!
    at X (/Users/belarusrulez/IdeaProjects/gray-area-us/packages/web/.next/server/chunks/3287.js:10:24415)
    at /Users/belarusrulez/IdeaProjects/gray-area-us/packages/web/.next/server/chunks/3287.js:10:24546
    at v (/Users/belarusrulez/IdeaProjects/gray-area-us/packages/web/.next/server/chunks/3287.js:1:127979)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/belarusrulez/IdeaProjects/gray-area-us/packages/web/.next/server/chunks/3287.js:1:268781
    at async /Users/belarusrulez/IdeaProjects/gray-area-us/packages/web/.next/server/chunks/3287.js:1:252751
    at async /Users/belarusrulez/IdeaProjects/gray-area-us/packages/web/.next/server/chunks/3287.js:1:267524
    at async /Users/belarusrulez/IdeaProjects/gray-area-us/packages/web/.next/server/chunks/3287.js:1:217309
    at async c (/Users/belarusrulez/IdeaProjects/gray-area-us/packages/web/.next/server/chunks/9595.js:7:8832)
    at async p (/Users/belarusrulez/IdeaProjects/gray-area-us/packages/web/.next/server/chunks/9595.js:7:9055) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '30f185da-bb30-4f9b-9826-9f06e2aa7330',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'ValidationException'
}
```

in dev everything works
I tried to deploy infrastructure first and set all secrets using 
npx sst secrets load.
still getting the same issue

If I do 
npx sst dev --stage dev
npx sst deploy --stage dev

I don't get the error and it says it's deployed successfully.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
