### ISSUE TITLE
Cannot deploy new SvelteKit app

### ISSUE THREAD

**Issue by aldo-roman** [sst/sst#3808]
Hello everyone,
I've created a new SvelteKit app and trying to deploy with SST.

I already changed the svelte config `vitePreprocess` import which was wrong (also reported in #3728), and it runs and compiles. It fails to deploy with this output:

```
There was a problem bundling the SSR function for the "ServerFunction" Site.
Could not resolve "devalue"
.svelte-kit/svelte-kit-sst/server/chunks/stores.js
3 │ import "devalue";
Could not resolve "devalue"
.svelte-kit/svelte-kit-sst/server/index.js
3 │ import * as devalue from "devalue";
Could not resolve "cookie"
.svelte-kit/svelte-kit-sst/server/index.js
5 │ import { parse, serialize } from "cookie";
Could not resolve "set-cookie-parser"
.svelte-kit/svelte-kit-sst/server/index.js
6 │ import * as set_cookie_parser from "set-cookie-parser";
Could not resolve "@sveltejs/kit/node/polyfills"
.svelte-kit/svelte-kit-sst/server/lambda-handler/index.js
3 │ import { installPolyfills } from "@sveltejs/kit/node/polyfills";

Trace: Error: There was a problem bundling the SSR function for the "ServerFunction" Site.
Could not resolve "devalue"
.svelte-kit/svelte-kit-sst/server/chunks/stores.js
3 │ import "devalue";
Could not resolve "devalue"
.svelte-kit/svelte-kit-sst/server/index.js
3 │ import * as devalue from "devalue";
Could not resolve "cookie"
.svelte-kit/svelte-kit-sst/server/index.js
5 │ import { parse, serialize } from "cookie";
Could not resolve "set-cookie-parser"
.svelte-kit/svelte-kit-sst/server/index.js
6 │ import * as set_cookie_parser from "set-cookie-parser";
Could not resolve "@sveltejs/kit/node/polyfills"
.svelte-kit/svelte-kit-sst/server/lambda-handler/index.js
3 │ import { installPolyfills } from "@sveltejs/kit/node/polyfills";
    at SsrFunction.buildAssetFromHandler (file:///Users/aldoromannurena/workspace/efficraft-app/node_modules/sst/constructs/SsrFunction.js:225:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/aldoromannurena/workspace/efficraft-app/node_modules/sst/constructs/SsrFunction.js:65:19
    at process.<anonymous> (file:///Users/aldoromannurena/workspace/efficraft-app/node_modules/sst/cli/sst.js:58:21)
    at process.emit (node:events:530:35)
    at process.emit (node:domain:488:12)
    at process._fatalException (node:internal/process/execution:178:25)
    at processPromiseRejections (node:internal/process/promises:289:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

I tried deleting `node_modules` and `package-lock.json` and reinstalling, with the same result. 

The S3 bucket were created and there is access, but nothing was deployed.

Any clues?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
