### ISSUE TITLE
RDS proxy for Drizzle

### ISSUE THREAD

**Issue by lxhan** [sst/sst#3940]
Is RDS proxy required for Next.js Drizzle stack? I have this setup:
```ts
const vpc = new sst.aws.Vpc('MyVpc');
const bucket = new sst.aws.Bucket('MyBucket', {
    access: 'public',
});
const rds = new sst.aws.Postgres('MyDb', { vpc });
new sst.aws.Nextjs('CarCrm', {
  vpc,
  link: [bucket],
});
```
and if I try to run `drizzle-kit migrate` I'm getting connection timeout/refused/reset. 
I tried to add `nat: 'ec2'` and `bastion: true` option to vpc, tunnel is installed but still can't apply migration or do anything with database.
In this updated guide https://sst.dev/docs/start/aws/drizzle there is a proxy option and when I add this to my rds migrations applying, but if I try to seed my db I still get connection reset.

Is there any way to avoid using proxy with this setup since it costs even more than t4g.micro instance itself?

**Comment by lxhan** [comment]
I've ended up setting up public database and not linking it. Not secure but at least for development if there is no way to opt out from proxy I didn't find any other option. 

> The RDS proxy helps with all the connections that Lambda functions make.

I'm playing around with it for couple of days and didn't notice any connection issues without proxy, can someone please explain how proxy help with connections that lambda make?

**Comment by Trajko00** [comment]
Well something similar is happening to me as well - dev command from tutorial works but migrations not at all.
Btw did not forget to install tunnel
```
export const vpc = new sst.aws.Vpc("TestVPC", {
    nat: 'ec2',
    bastion: true,
});
```

```
import { vpc } from "./vpc";

export const rds = new sst.aws.Postgres("TestDatabase", { vpc, proxy: true });
```

now, running yarn sst dev - will do fine
 ```
async run() {
    const {cluster} = await import("./infra/cluster");
    const {backendServiceConfig} = await import('./infra/backend')
    const {rds} = await import('./infra/database')
    const {queue} = await import('./infra/queue')
    const {frontend} = await import('./infra/frontend')

    cluster.addService("ApiService", {
      ...backendServiceConfig,
    });

    new sst.x.DevCommand("Studio", {
      link: [rds],
      dev: {
        command: "yarn workspace backend drizzle-kit studio",
      },
    });

    new sst.x.DevCommand("Backend", {
      link: [rds,queue],
      dev: {
        command: "yarn workspace backend dev",
      },
    });

  }
```

but running `yarn workspace backend db migrate` gets me this
```
Reading config file '/Users/Dev/Personal/Test/apps/backend/drizzle.config.ts'
Using 'pg' driver for database querying
[⣟] applying migrations...AggregateError
    at /Users/Dev/Personal/Test/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PgDialect.migrate (/Users/Dev/Personal/Test/node_modules/src/pg-core/dialect.ts:84:3)
    at migrate (/Users/Dev/Personal/Test/node_modules/src/node-postgres/migrator.ts:10:2) {
  code: 'ETIMEDOUT',
  [errors]: [
    Error: connect ETIMEDOUT 10.0.13.98:5432
        at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
        at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -60,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '10.0.13.98',
      port: 5432
    },
    Error: connect ETIMEDOUT 10.0.7.142:5432
        at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
        at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -60,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '10.0.7.142',
      port: 5432
    }
  ]
}
✕  exit status 1
```

Also migrations never worked for me no matter what

**Comment by Trajko00** [comment]
Well something similar is happening to me as well - dev command from tutorial works but migrations not at all.
Btw did not forget to install tunnel
```
export const vpc = new sst.aws.Vpc("TestVPC", {
    nat: 'ec2',
    bastion: true,
});
```

```
import { vpc } from "./vpc";

export const rds = new sst.aws.Postgres("TestDatabase", { vpc, proxy: true });
```

now, running yarn sst dev - will do fine
 ```
async run() {
    const {cluster} = await import("./infra/cluster");
    const {backendServiceConfig} = await import('./infra/backend')
    const {rds} = await import('./infra/database')
    const {queue} = await import('./infra/queue')
    const {frontend} = await import('./infra/frontend')

    cluster.addService("ApiService", {
      ...backendServiceConfig,
    });

    new sst.x.DevCommand("Studio", {
      link: [rds],
      dev: {
        command: "yarn workspace backend drizzle-kit studio",
      },
    });

    new sst.x.DevCommand("Backend", {
      link: [rds,queue],
      dev: {
        command: "yarn workspace backend dev",
      },
    });

  }
```

but running `yarn workspace backend db migrate` gets me this
```
Reading config file '/Users/Dev/Personal/Test/apps/backend/drizzle.config.ts'
Using 'pg' driver for database querying
[⣟] applying migrations...AggregateError
    at /Users/Dev/Personal/Test/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PgDialect.migrate (/Users/Dev/Personal/Test/node_modules/src/pg-core/dialect.ts:84:3)
    at migrate (/Users/Dev/Personal/Test/node_modules/src/node-postgres/migrator.ts:10:2) {
  code: 'ETIMEDOUT',
  [errors]: [
    Error: connect ETIMEDOUT 10.0.xx.xx:5432
        at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
        at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)
        at createConnectionError (node:net:1634:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -60,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '10.0.xx.xx',
      port: 5432
    },
    Error: connect ETIMEDOUT 10.0.x.xxx:5432
        at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
        at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -60,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '10.0.x.xxx',
      port: 5432
    }
  ]
}
✕  exit status 1
```

Also migrations never worked for me no matter what

**Comment by jayair** [comment]
Is your tunnel running when you are running migrations?

**Comment by alexdev888** [comment]
I fixed this problem by linking rds instance. Here is an example:

```typescript
new sst.aws.Nextjs("MyWeb", {
  vpc: vpc,
  link: [bucket, rds],
});

**Comment by mharrvic** [comment]
> I fixed this problem by linking rds instance. Here is an example:
> 
> ```ts
> new sst.aws.Nextjs("MyWeb", {
>   vpc: vpc,
>   link: [bucket, rds],
> });
> ```

This works on my end!

**Comment by jayair** [comment]
Closing this for now.
