### ISSUE TITLE
cloudflare.StaticSite does not work

### ISSUE THREAD

**Issue by Ernxst** [sst/sst#3952]
I believe this is related to [1044](https://github.com/sst/ion/issues/1044) but this also happens with `sst deploy`. Not sure when this issue was introduced, but I noticed a while back the react dev build was included in my cloudflare worker, despite me having:

```
define: {
  "process.env.NODE_ENV": "'production'"
}
```

In the `build.esbuild` of my worker. 

In the output artefact, I can see that `process.env.NODE_ENV` isn't replaced at all. In a separate app, I tried to create a cloudflare static site, but that never worked, failing with the following error:

```json
"exceptions": [
  {
    "stack": "    at respond (worker.mjs:50:7)\n    at fetch (worker.mjs:15:38)",
    "name": "ReferenceError",
    "message": "SST_ASSET_MANIFEST is not defined",
    "timestamp": 1729071695262
  }
]
```

Inspecting the source code, I can see that [`SST_ASSET_MANIFEST`](https://github.com/sst/ion/blob/1c5127709697d3815d2c9f4a4ac0588d92f81e54/platform/functions/cf-static-site-router-worker/index.ts#L2) is also supposed to be [replaced](https://github.com/sst/ion/blob/1c5127709697d3815d2c9f4a4ac0588d92f81e54/platform/src/components/cloudflare/static-site.ts#L436) with the actual manifest JSON using `define`, so I can only assume these two things broke at the same time.

Here's a reproduction [repo](https://github.com/Ernxst/sst-esbuild-define); after running `sst deploy`, you'll still see unreplaced `process.env.NODE_ENV` in the output artifact of the worker and unreplaced `SST_ASSET_MANIFEST` in the web router output file. Trying to access the url of the static site takes you to an error page and inspecting the logs will show the same error as above.

**Comment by Ernxst** [comment]
Tried again on latest (3.3.13) and it's still broken. I'm pretty sure _all_ of the cloudflare web components use esbuild define so I'd assume they're all broken too? Downgraded  to 3.0.124, the version before the bundling was moved to go, and it works; tryied 3.0.125 and it's broken. Seems [this](https://github.com/sst/sst/commit/6303d91eb84592322971d3dd759d524c8c273aff) commit broke it.

**Comment by jayair** [comment]
We haven't released this yet. We'll do another pass at the Cloudflare components at some point.

**Comment by ChiChuRita** [comment]
Can you tell us approximately when that will happen?
Thanks!

**Comment by tung-dnt** [comment]
aws functions are still encountering issues, hope SST can fix thif ASAP
