### ISSUE TITLE
SST Console Autodeploy fails with pulumi-aws v6.55.0: TypeError: pulumi.runtime.invokeOutput is not a function

### ISSUE THREAD

**Issue by Han-Joon-Hyeok** [sst/sst#3960]
# Enviornment

- SST ion: 0.1.95
- pulumi-aws: 6.55.0
- Next.js: 14.0.4

# Description
When deploying a Next.js app to AWS using SST ion with `autodeploy` in the SST Console, I encountered an error. The application was built successfully and worked well locally, but the deployment to AWS failed.

# Full Error Stack Trace
```bash
Running program '/tmp/repo/.sst/platform/sst.config.1728934396611.mjs' failed with an unhandled exception:
TypeError: pulumi.runtime.invokeOutput is not a function
    at getPartitionOutput (/tmp/repo/.sst/platform/node_modules/@pulumi/getPartition.ts:89:27)
    at normalizePartition (file:///tmp/repo/.sst/platform/src/components/aws/ssr-site.ts:194:12)
    at prepare (file:///tmp/repo/.sst/platform/src/components/aws/ssr-site.ts:172:21)
    at new Nextjs (file:///tmp/repo/.sst/platform/src/components/aws/nextjs.ts:512:45)
    at run (file:///tmp/repo/sst.config.ts:34:5)
    at run (file:///tmp/repo/.sst/platform/src/auto/run.ts:33:26)
    at file:///tmp/repo/eval.ts:4:28
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:432:15)
```

# Code Snippet

```typescript

// sst.config.ts
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "frontend",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
      providers: {
        aws: {
          region: "ap-northeast-2",
        },
      },
    };
  },
  console: {
    autodeploy: {
      target(event) {
        if (
          event.type === "branch" &&
          event.action === "pushed" &&
          event.branch === "main"
        ) {
          return {
            stage: "production",
          };
        }
      },
    },
  },
  async run() {
    new sst.aws.Nextjs("Habitpayfrontend", {
      domain: "habitpay.link",
    });
  },
});
```

# Questions

1. I found a similar issue([Link](https://github.com/sst/sst/issues/3882)) when using pulumi-aws version `6.53.0`, and I was able to resolve it by downgrading to version `6.52.0`. However, I'm curious to understand what exactly caused this error when upgrading to version `6.53.0` and later versions.
    ```diff
    export default $config({
      app(input) {
        return {
          name: "frontend",
          removal: input?.stage === "production" ? "retain" : "remove",
          home: "aws",
          providers: {
            aws: {
              region: "ap-northeast-2",
    +         version: "6.52.0",
            },
          },
        };
      },
    ```

2. Is there a way to use GitHub Actions to perform a dry-run of an SST deployment to check if it will succeed?

**Comment by jayair** [comment]
In this case it seemed like an issue with the AWS provider. So pinning the version like that is probably the safest approach here.

**Comment by Han-Joon-Hyeok** [comment]
Thanks for your answer. I hope the underlying issue gets resolved soon. 🙂
