### ISSUE TITLE
Error: SSM: GetParameter - exceeded maximum number of attempts, 3

### ISSUE THREAD

**Issue by alexanderbh** [sst/sst#4063]
## Issue

I am migrating a V2 app to V3/Ion and I get this error a lot (almost every time I start it) when running `sst dev` or `sst deploy`.

I have around 270 functions. I have only started noticing this as I have added more functions. 

```
✕  Failed
   Error: operation error SSM: GetParameter, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: 12f20059-7cd2-48f9-a38f-7078327f8fa8, api error ThrottlingException: Rate exceeded
       at IncomingMessage.<anonymous> (file:///Users/--/.sst/platform/src/components/rpc/rpc.ts:42:22)
       at IncomingMessage.emit (node:events:529:35)
       at IncomingMessage.emit (node:domain:489:12)
       at endReadableNT (node:internal/streams/readable:1400:12)
       at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

This is getting really frustrating where maybe only 1 in 4 deployments work without these errors.

**Comment by alexanderbh** [comment]
Am I the only one that experience this? It seems kinda random. It happens both for `sst dev` and `sst deploy`. It happens so much we have to have our CI deploy multiple times just in case this happens. It is the amount of functions we have?

```
Run pnpm sst deploy --stage=pr295
SST 3.2.38  ready!
➜  App:        ---
   Stage:      pr295
~  Deploy
|  Error       
|  Error: operation error SSM: GetParameter, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: ef42d165-2d36-460b-aa65-3ccd0686cd29, api error ThrottlingException: Rate exceeded
|      at IncomingMessage.<anonymous> (file:///home/ghrunner/actions-runner/_work/monorepo/monorepo/.sst/platform/src/components/rpc/rpc.ts:42:22)
|      at IncomingMessage.emit (node:events:531:35)
|      at IncomingMessage.emit (node:domain:488:[12](https://github.com/---/actions/runs/11496997135/job/31999767667#step:12:13))
|      at endReadableNT (node:internal/streams/readable:1696:12)
|      at processTicksAndRejections (node:internal/process/task_queues:82:21)
|  Error       
|  Error: operation error SSM: GetParameter, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: 06ba4095-8e[14](https://github.com/---/actions/runs/11496997135/job/31999767667#step:12:15)-44c1-ac53-c47503676f70, api error ThrottlingException: Rate exceeded
|      at IncomingMessage.<anonymous> (file:///home/ghrunner/actions-runner/_work/monorepo/monorepo/.sst/platform/src/components/rpc/rpc.ts:42:22)
|      at IncomingMessage.emit (node:events:531:35)
|      at IncomingMessage.emit (node:domain:488:12)
|      at endReadableNT (node:internal/streams/readable:1696:12)
|      at processTicksAndRejections (node:internal/process/task_queues:82:21)
|  Error       
|  Error: operation error SSM: GetParameter, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: 77768a39-e074-49bc-96f3-7b0374b03f9d, api error ThrottlingException: Rate exceeded
|      at IncomingMessage.<anonymous> (file:///home/ghrunner/actions-runner/_work/monorepo/monorepo/.sst/platform/src/components/rpc/rpc.ts:42:22)
|      at IncomingMessage.emit (node:events:531:35)
|      at IncomingMessage.emit (node:domain:488:12)
|      at endReadableNT (node:internal/streams/readable:1696:12)
|      at processTicksAndRejections (node:internal/process/task_queues:82:21)
|  Error       
|  Error: operation error SSM: GetParameter, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: cf9d8e52-c1eb-43d8-a2d7-5678bb7c899b, api error ThrottlingException: Rate exceeded
|      at IncomingMessage.<anonymous> (file:///home/ghrunner/actions-runner/_work/monorepo/monorepo/.sst/platform/src/components/rpc/rpc.ts:42:22)
|      at IncomingMessage.emit (node:events:531:35)
|      at IncomingMessage.emit (node:domain:488:12)
|      at endReadableNT (node:internal/streams/readable:1696:12)
|      at processTicksAndRejections (node:internal/process/task_queues:82:21)
|  Error       
|  Error: operation error SSM: GetParameter, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: bc1bddd3-299f-4489-a2dc-21a8cdd95040, api error ThrottlingException: Rate exceeded
|      at IncomingMessage.<anonymous> (file:///home/ghrunner/actions-runner/_work/monorepo/monorepo/.sst/platform/src/components/rpc/rpc.ts:42:22)
|      at IncomingMessage.emit (node:events:531:35)
|      at IncomingMessage.emit (node:domain:488:12)
|      at endReadableNT (node:internal/streams/readable:1696:12)
|      at processTicksAndRejections (node:internal/process/task_queues:82:21)
|  Error       
|  Error: operation error SSM: GetParameter, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: 3d87b1df-7c43-4fae-aaf4-0657c25f0[15](https://github.com/----/actions/runs/11496997135/job/31999767667#step:12:16)e, api error ThrottlingException: Rate exceeded
|      at IncomingMessage.<anonymous> (file:///home/ghrunner/actions-runner/_work/monorepo/monorepo/.sst/platform/src/components/rpc/rpc.ts:42:22)
|      at IncomingMessage.emit (node:events:531:35)
|      at IncomingMessage.emit (node:domain:488:12)
|      at endReadableNT (node:internal/streams/readable:[16](https://github.com/----/actions/runs/11496997135/job/31999767667#step:12:17)96:12)
|      at processTicksAndRejections (node:internal/process/task_queues:82:21)
|  Error       
|  Error: operation error SSM: GetParameter, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: f63f87[18](https://github.com/---/actions/runs/11496997135/job/31999767667#step:12:19)-f030-4480-b5af-e5f6e4b87c3d, api error ThrottlingException: Rate exceeded
|      at IncomingMessage.<anonymous> (file:///home/ghrunner/actions-runner/_work/monorepo/monorepo/.sst/platform/src/components/rpc/rpc.ts:42:22)
|      at IncomingMessage.emit (node:events:531:35)
|      at IncomingMessage.emit (node:domain:488:12)
|      at endReadableNT (node:internal/streams/readable:1696:12)
|      at processTicksAndRejections (node:internal/process/task_queues:82:[21](https://github.com/---/actions/runs/11496997135/job/31999767667#step:12:22))
