### ISSUE TITLE
Solid Start Deploy Error

### ISSUE THREAD

**Issue by bc0x** [sst/sst#4235]
Hey I'm getting an issue when trying to deploy a SolidStart app inside a **monorepo**.

`bunx sst dev` works fine, but when actually deploying with `bunx sst deploy` there is an error I can't seem to figure out. See the output below.

```
smart-strike git:(main) ✗ bunx sst deploy
SST ❍ ion 0.1.111  ready!

➜  App:        smart-strike
   Stage:      bcox

~  Deploy

|  Created     SmartStrikeFE sst:aws:SolidStart → SmartStrikeFEAssets sst:aws:Bucket
vinxi v0.4.1
|  Created     SmartStrikeFE sst:aws:SolidStart → SmartStrikeFEAssetsId random:index:RandomId
|  Created     SmartStrikeFE sst:aws:SolidStart → SmartStrikeFES3AccessControl sst:aws:OriginAccessControl


⚙  Building your app...
removing /Users/bcox/dev/smart-strike/packages/frontend/.vinxi/build/ssr
removing /Users/bcox/dev/smart-strike/packages/frontend/.vinxi/build/client
removing /Users/bcox/dev/smart-strike/packages/frontend/.vinxi/build/server-fns


📦 Compiling ssr router...
vinxi building router ssr in http mode
vite v5.4.1 building SSR bundle for production...
transforming...
|  Updated     BitcoinUpdater sst:aws:Cron → BitcoinUpdaterHandlerRole aws:iam:Role
|  Created     OptionUpdater sst:aws:Cron → OptionUpdaterHandlerCode aws:s3:BucketObjectv2
|  Updated     OptionUpdater sst:aws:Cron → OptionUpdaterHandlerRole aws:iam:Role
|  Updated     StockUpdater sst:aws:Cron → StockUpdaterHandlerRole aws:iam:Role
|  Created     BitcoinUpdater sst:aws:Cron → BitcoinUpdaterHandlerCode aws:s3:BucketObjectv2
|  Created     StockUpdater sst:aws:Cron → StockUpdaterHandlerCode aws:s3:BucketObjectv2
|  Created     SmartStrikeFE sst:aws:SolidStart → SmartStrikeFEAssetsBucket aws:s3:BucketV2 (2.1s)
|  Created     SmartStrikeFE sst:aws:SolidStart → SmartStrikeFEAssetsPublicAccessBlock aws:s3:BucketPublicAccessBlock
|  Created     SmartStrikeFE sst:aws:SolidStart → SmartStrikeFEAssetsCors aws:s3:BucketCorsConfigurationV2
|  Created     SmartStrikeFE sst:aws:SolidStart → SmartStrikeFEAssetsPolicy aws:s3:BucketPolicy
✓ 1602 modules transformed.
rendering chunks...
.vinxi/build/ssr/.vite/manifest.json              2.48 kB
.vinxi/build/ssr/assets/ssr-C6q4osKn.css         12.94 kB
.vinxi/build/ssr/bitcoin.js                       0.87 kB
.vinxi/build/ssr/index.js                         0.87 kB
.vinxi/build/ssr/assets/createAsync-3P_WoQYp.js   1.16 kB
.vinxi/build/ssr/login.js                         1.76 kB
.vinxi/build/ssr/todo.js                          5.13 kB
.vinxi/build/ssr/investments.js                   9.31 kB
.vinxi/build/ssr/ssr.js                          21.26 kB
.vinxi/build/ssr/assets/stocks-BJ7rSaNi.js       26.96 kB
✓ built in 2.65s
✔ build done


📦 Compiling client router...
vinxi building router client in client mode
vite v5.4.1 building for production...
transforming...
✓ 1603 modules transformed.
rendering chunks...
computing gzip size...
.vinxi/build/client/_build/server-functions-manifest.json   0.29 kB │ gzip:  0.12 kB
.vinxi/build/client/_build/.vite/manifest.json              2.37 kB │ gzip:  0.45 kB
.vinxi/build/client/_build/assets/client-C6q4osKn.css      12.94 kB │ gzip:  3.19 kB
.vinxi/build/client/_build/assets/index-DcCnCZwM.js         0.67 kB │ gzip:  0.45 kB
.vinxi/build/client/_build/assets/bitcoin-kkUGINjn.js       0.67 kB │ gzip:  0.45 kB
.vinxi/build/client/_build/assets/login-BkwgcRIZ.js         1.57 kB │ gzip:  0.75 kB
.vinxi/build/client/_build/assets/createAsync-DN5hcHrX.js   5.65 kB │ gzip:  2.29 kB
.vinxi/build/client/_build/assets/todo-BXZjKK-x.js          6.15 kB │ gzip:  2.52 kB
.vinxi/build/client/_build/assets/investments-C77wO34b.js  11.88 kB │ gzip:  3.25 kB
.vinxi/build/client/_build/assets/client-CFNsjIO1.js       21.88 kB │ gzip:  8.56 kB
.vinxi/build/client/_build/assets/stocks-BYghSAiB.js       61.97 kB │ gzip: 21.01 kB
✓ built in 1.99s
✔ build done


📦 Compiling server-fns router...
vinxi building router server-fns in http mode
vite v5.4.1 building SSR bundle for production...
transforming...
✓ 1596 modules transformed.
rendering chunks...
.vinxi/build/server-fns/_server/.vite/manifest.json       4.29 kB
.vinxi/build/server-fns/_server/assets/app-C6q4osKn.css  12.94 kB
.vinxi/build/server-fns/_server/entry.mjs                 0.47 kB
.vinxi/build/server-fns/_server/c_6012.mjs                0.50 kB
.vinxi/build/server-fns/_server/bitcoin.mjs               0.92 kB
.vinxi/build/server-fns/_server/index.mjs                 0.92 kB
.vinxi/build/server-fns/_server/createAsync.mjs           1.16 kB
.vinxi/build/server-fns/_server/c_6003.mjs                1.45 kB
.vinxi/build/server-fns/_server/login.mjs                 1.83 kB
.vinxi/build/server-fns/_server/stocks.sql.mjs            2.15 kB
.vinxi/build/server-fns/_server/c_6228.mjs                2.28 kB
.vinxi/build/server-fns/_server/c_6345.mjs                3.09 kB
.vinxi/build/server-fns/_server/todo.mjs                  5.25 kB
.vinxi/build/server-fns/_server/server-fns.mjs            9.24 kB
.vinxi/build/server-fns/_server/investments.mjs           9.44 kB
.vinxi/build/server-fns/_server/app.mjs                  12.20 kB
.vinxi/build/server-fns/_server/user.mjs                 19.84 kB
✓ built in 1.87s
✔ build done
$ vinxi build
Cannot extend config from `aws-lambda-streaming` in /Users/bcox/dev/smart-strike/packages/frontend

 ERROR  Nitro entry is missing! Is "aws-lambda-streaming" preset correct?

  at loadOptions (/Users/bcox/dev/smart-strike/node_modules/nitropack/dist/nitro.mjs:4803:11)
  at async createNitro (/Users/bcox/dev/smart-strike/node_modules/nitropack/dist/nitro.mjs:5086:19)
  at async createBuild (/Users/bcox/dev/smart-strike/node_modules/vinxi/lib/build.js:64:16)
  at async Object.run (/Users/bcox/dev/smart-strike/node_modules/vinxi/bin/cli.mjs:227:5)
  at async runCommand (/Users/bcox/dev/smart-strike/node_modules/citty/dist/index.mjs:316:16)
  at async runCommand (/Users/bcox/dev/smart-strike/node_modules/citty/dist/index.mjs:307:11)
  at async runMain (/Users/bcox/dev/smart-strike/node_modules/citty/dist/index.mjs:445:7) 



 ERROR  Nitro entry is missing! Is "aws-lambda-streaming" preset correct?

error: script "build" exited with code 1
|  Error       SmartStrikeFE sst:aws:SolidStart → SmartStrikeFEBuild sst:Run
|  command exited with code 1
|  Updated     StockUpdater sst:aws:Cron → StockUpdaterHandlerFunction aws:lambda:Function (6.8s)
|  Updated     BitcoinUpdater sst:aws:Cron → BitcoinUpdaterHandlerFunction aws:lambda:Function (6.9s)
|  Updated     OptionUpdater sst:aws:Cron → OptionUpdaterHandlerFunction aws:lambda:Function (6.9s)

✕  Failed    
   SmartStrikeFE sst:aws:SolidStart → SmartStrikeFEBuild sst:Run
   command exited with code 1
```

Here is my `app.config.ts`
```typescript
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  server: {
    preset: "aws-lambda-streaming",
  },
});

``` 

Also worth noting that I can navigate to the frontend directory and build the app via `bun run build`, **BUT** I have to change the server preset to `aws-lambda` instead of `aws-lambda-streaming`. 

`bunx sst deploy` doesn't work with either preset. 

Lmk what info is needed, or if this is an issue I should open elsewhere. Just hoping to collect some more info about why this may be happening.

**Comment by TheKnightCoder** [comment]
for anyone newly finding this, I think the new nitro `app.config.ts` is this

```
import { defineConfig } from '@solidjs/start/config'

export default defineConfig({
  server: {
    compatibilityDate: '2024-11-05',
    preset: 'aws-lambda',
    awsLambda: {
      streaming: true,
    },
  },
})
```
