### ISSUE TITLE
Redirects are not supported when DNS is disabled

### ISSUE THREAD

**Issue by AlissonRS** [sst/sst#4287]
Would be nice if this was supported, as long as we provided an existing ACM Certificate ARN.

SST would take care of creating the extra distribution + S3 Website for redirects, with the appropriate alternate domain name and the ACM Certificate.

This is useful if DNS is not managed within AWS, so we'd just need to take care of creating the CNAME records pointing to the cloudfront hostnames.

As of now, adding `redirects` makes SST try creating a new ACM Certificate and ignore the ARN provided, which is a related issue logged here sst/sst#4288

**Comment by Prinzhorn** [comment]
Not only does it currently not work it seems to cause an inconsistent state.

I had this (with my actual domain):

```js
domain: {
  name: 'example.com',
  redirects: ['www.example.com'],
  dns: false,
  cert: 'arn:aws:acm:us-east-1:...',
},
```

Running `deploy` will log:

```
Error: Redirects are not supported when DNS is disabled
    at file:///code/file-manager/src/.sst/platform/src/components/aws/cdn.ts:337:17
    at /code/file-manager/src/.sst/platform/node_modules/@pulumi/output.ts:490:31
    at Generator.next (<anonymous>)
    at /code/file-manager/src/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/code/file-manager/src/.sst/platform/node_modules/@pulumi/pulumi/output.js:17:12)
    at applyHelperAsync (/code/file-manager/src/.sst/platform/node_modules/@pulumi/pulumi/output.js:298:12)
    at /code/file-manager/src/.sst/platform/node_modules/@pulumi/output.ts:352:13

TypeError: Cannot read properties of undefined (reading 'createAlias')
    at file:///code/file-manager/src/.sst/platform/src/components/aws/https-redirect.ts:138:13
    at /code/file-manager/src/.sst/platform/node_modules/@pulumi/output.ts:490:31
    at Generator.next (<anonymous>)
    at /code/file-manager/src/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/code/file-manager/src/.sst/platform/node_modules/@pulumi/pulumi/output.js:17:12)
    at applyHelperAsync (/code/file-manager/src/.sst/platform/node_modules/@pulumi/pulumi/output.js:298:12)
    at /code/file-manager/src/.sst/platform/node_modules/@pulumi/output.ts:352:13
```

but it already created a second CloudFront distribution "Redirect to example.com from www.example.com" and the redirect S3 bucket.

In fact running it multiple times will create a new bucket each time and NOT remove it. That's pretty bad, no? Why does it not clean up? I currently have three "redirect" buckets and a distribution that is "Deploying" (but SST finished and didn't wait for it). I never interrupted SST and let it run.

Edit: clarification: Removing `redirects` and running `deploy` again will remove the distributions and wait for it to finish removing. However, the buckets stay. So this is definitely bad and inconsistent.

1. Why is an exception thrown when it seems to be able to setup everything correctly?
2. Why does the exception not cause everything to be rolled back?
3. Why does removing `redirects` and deploying again only clean up the distribution and not the bucket?

Edit2: Another side note, which might be related: I actually had to do `dns: false as any,` because the typing seems to be broken.

**Comment by fwang** [comment]
Released in v3.14.25. You can now configure `redirects` when `dns: false`.

re @Prinzhorn 
> 1. Why is an exception thrown when it seems to be able to setup everything correctly?

This was a bug. This is irrelevant now b/c redirects are allowed.

> 2. Why does the exception not cause everything to be rolled back?

Unused resources will be removed after the next successful deploy.

> 3. Why does removing redirects and deploying again only clean up the distribution and not the bucket?

Likely `app.remove` is set to `retain` in sst.config.ts.

**Comment by Prinzhorn** [comment]
@fwang thanks a lot!

**Comment by Prinzhorn** [comment]
@fwang I might be doing something wrong again, but after deploying here's what I get:

```
domain: {
  name: 'example.com',
  redirects: ['www.example.com'],
  dns: false,
  cert: 'arn:aws:acm:us-east-1:...',
},
```

http works (probably doesn't run the CF function?) :

```
$ curl --include http://www.example

HTTP/1.1 301 Moved Permanently
Server: CloudFront
Date: Fri, 16 May 2025 05:47:32 GMT
Content-Type: text/html
Content-Length: 167
Connection: keep-alive
Location: https://www.abconcepts-odt.de/
X-Cache: Redirect from cloudfront
Via: 1.1 2e4a0520ad8fe16707823b20e9441e08.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: FRA56-C2
X-Amz-Cf-Id: IaFN4vxP5WdSmBXRDLHUIsX83wji86o5a-tjJaTIy10w_xsGV4uJfw==

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```

https does not:

```
curl --include https://www.example.com

HTTP/2 503 
server: CloudFront
date: Fri, 16 May 2025 05:49:20 GMT
content-type: text/html
content-length: 982
x-cache: FunctionValidationError from cloudfront
via: 1.1 a7631312afe99e40229aa0da70662112.cloudfront.net (CloudFront)
x-amz-cf-pop: FRA56-C2
x-amz-cf-id: 5Nx5pmgchhFWNz7lOPoiQMQneKDj9-9N-Wpkp4j-Rx4plSH4dVjDCQ==

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>503 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The CloudFront function returned an invalid value: the value must be an object.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 5Nx5pmgchhFWNz7lOPoiQMQneKDj9-9N-Wpkp4j-Rx4plSH4dVjDCQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

This is the CloudFront function generated by SST (copied from the AWS Console):

```

import cf from "cloudfront";
async function handler(event) {
  
if (event.request.headers.host.value.includes('cloudfront.net')) {
  return {
    statusCode: 403,
    statusDescription: 'Forbidden',
    body: {
      encoding: "text",
      data: '<html><head><title>403 Forbidden</title></head><body><center><h1>403 Forbidden</h1></center></body></html>'
    }
  };
}
}
```

Shouldn't this `return event.request` for the regular case? Currently it returns undefined.

Edit: can confirm, adding `return event.request` makes it work, I edited in the AWS console.

Edit: that whole function generation code is _wild_ and no wonder this slipped through:

https://github.com/sst/sst/blob/d5eec560524dd015187bdfc34ab582be7923e0ee/platform/src/components/aws/router.ts#L1935-L2160

There must be a better way? Like storing this as `.liquid.js` file (so you get syntax highlight and formatting) but it's actually a template (e.g. liquidjs) in disguise. So you put the control structures into js comments like:

```js
// {% if foo == "FOO" %}
if (event.request.headers.host.value.includes('cloudfront.net')) {
  return {
    statusCode: 403,
    statusDescription: 'Forbidden',
    body: {
      encoding: "text",
      data: '<html><head><title>403 Forbidden</title></head><body><center><h1>403 Forbidden</h1></center></body></html>'
    }
  };
}
// {% endif %}
```

and stuff like `CF_BLOCK_CLOUDFRONT_URL_INJECTION` ist just a partial in a `.liquid.js` file that can be included like `{% render 'cf_block_cloudfront_url_injection' %}`

**Comment by fwang** [comment]
Released v3.14.27

Nice catch @Prinzhorn!
