### ISSUE TITLE
ReferenceError: crypto is not defined for 0.1.64

### ISSUE THREAD

**Issue by kwigley** [sst/sst#4357]
after upgrading to 0.1.64 I get the following error on deploy (only in github/console builds)
```
Running program '/tmp/repo/.sst/platform/sst.config.1722392645972.mjs' failed with an unhandled exception:
ReferenceError: crypto is not defined
    at file:///tmp/repo/.sst/platform/src/components/aws/cdn.ts:404:16
    at /tmp/repo/.sst/platform/node_modules/@pulumi/output.ts:402:31
    at Generator.next (<anonymous>)
    at /tmp/repo/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/repo/.sst/platform/node_modules/@pulumi/pulumi/output.js:17:12)
    at applyHelperAsync (/tmp/repo/.sst/platform/node_modules/@pulumi/pulumi/output.js:244:12)
    at /tmp/repo/.sst/platform/node_modules/@pulumi/output.ts:316:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I think regression was added here https://github.com/sst/ion/commit/0b21b1ee29014b5c87ada2893af6eec79d56b1b2

**Comment by agamm** [comment]
I don't know if it is related but I get:
```
Getting an error on the latest version of sst with nextjs:
./node_modules/.pnpm/sst@3.3.26/node_modules/sst/dist/resource.js:3:1

Module not found: Can't resolve 'crypto'
  1 | import { env } from "process";
  2 | import { readFileSync } from "fs";
> 3 | import crypto from "crypto";
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
