### ISSUE TITLE
I'm unable to use sharp on lambda (dev and deploy)

### ISSUE THREAD

**Issue by ajotaos** [sst/sst#4362]
I have a pnpm monorepo, with one of the packages making use of the `sharp` library and a different package importing the first one where the lambda function code is located:
```
.
--infra
----comicbook
------pages.ts

--packages
----backend
------comicbook
--------files
----------package.json (with sharp)
--------functions
```

So when I try to run the function without installing sharp, everything is fine and the function runs. But as soon as the function is triggered while importing the `sharp` library, I get the following message on the console (can't copy / past from the new Ion SST console)

On `sst dev`
![Screenshot 2024-07-30 at 9 15 07 AM](https://github.com/user-attachments/assets/72ea1dce-0331-464b-aa3c-77a327735fcf)

And on `sst deploy`

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Could not load the \"sharp\" module using the linux-arm64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=arm64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Could not load the \"sharp\" module using the linux-arm64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=arm64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
        "stack": [
            "Error: Could not load the \"sharp\" module using the linux-arm64 runtime",
            "Possible solutions:",
            "- Ensure optional dependencies can be installed:",
            "    npm install --include=optional sharp",
            "    yarn add sharp --ignore-engines",
            "- Ensure your package manager supports multi-platform installation:",
            "    See https://sharp.pixelplumbing.com/install#cross-platform",
            "- Add platform-specific dependencies:",
            "    npm install --os=linux --cpu=arm64 sharp",
            "- Consult the installation documentation:",
            "    See https://sharp.pixelplumbing.com/install",
            "    at 257 (/opt/nodejs/node_modules/sharp/index.js:10166:9)",
            "    at __webpack_require__ (/opt/nodejs/node_modules/sharp/index.js:10497:41)",
            "    at 7300 (/opt/nodejs/node_modules/sharp/index.js:5412:1)",
            "    at __webpack_require__ (/opt/nodejs/node_modules/sharp/index.js:10497:41)",
            "    at 1842 (/opt/nodejs/node_modules/sharp/index.js:5866:15)",
            "    at __webpack_require__ (/opt/nodejs/node_modules/sharp/index.js:10497:41)",
            "    at /opt/nodejs/node_modules/sharp/index.js:10514:37",
            "    at Object.<anonymous> (/opt/nodejs/node_modules/sharp/index.js:10517:12)",
            "    at Module._compile (node:internal/modules/cjs/loader:1358:14)",
            "    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Could not load the \"sharp\" module using the linux-arm64 runtime",
        "Possible solutions:",
        "- Ensure optional dependencies can be installed:",
        "    npm install --include=optional sharp",
        "    yarn add sharp --ignore-engines",
        "- Ensure your package manager supports multi-platform installation:",
        "    See https://sharp.pixelplumbing.com/install#cross-platform",
        "- Add platform-specific dependencies:",
        "    npm install --os=linux --cpu=arm64 sharp",
        "- Consult the installation documentation:",
        "    See https://sharp.pixelplumbing.com/install",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)",
        "    at process.emit (node:events:519:28)",
        "    at emitUnhandledRejection (node:internal/process/promises:250:13)",
        "    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)",
        "    at processPromiseRejections (node:internal/process/promises:470:17)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```

I'm not sure if this is the correct way to solve this (please advise if not), but I created a lambda layer of sharp with the options like and it seems to work on deploy:

```
layers: ['arn:aws:lambda:us-east-1:xxxxxxxxxxxxxxxxx:layer:sharp-layer:2'],
nodejs: {
  esbuild: {
    external: ['sharp'],
  },
}
```

But I can't get it to work on `sst dev`

I've also tried using:
```
nodejs: {
  install: ['sharp']
},
```

Placing this on the root `package.json`

```
	"pnpm": {
		"supportedArchitectures": {
			"cpu": ["x64", "arm64"],
			"os": ["linux", "current"]
		}
	}
```

Install sharp on `--no-install=false`

Using SST (not Ion) I was able to use sharp without any additional configuration to the function component, how would it be suggested now?

**Comment by clemwo** [comment]
Any update on this?  
I'm using it exactly like in the example and still get the error:

```
{
    "errorType": "Error",
    "errorMessage": "Could not load the \"sharp\" module using the linux-x64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=x64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
    "stack": [
        "Error: Could not load the \"sharp\" module using the linux-x64 runtime",
        "Possible solutions:",
        "- Ensure optional dependencies can be installed:",
        "    npm install --include=optional sharp",
        "- Ensure your package manager supports multi-platform installation:",
        "    See https://sharp.pixelplumbing.com/install#cross-platform",
        "- Add platform-specific dependencies:",
        "    npm install --os=linux --cpu=x64 sharp",
        "- Consult the installation documentation:",
        "    See https://sharp.pixelplumbing.com/install",
        "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/sharp.js:113:9)",
        "    at Module._compile (node:internal/modules/cjs/loader:1469:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1288:32)",
        "    at Module._load (node:internal/modules/cjs/loader:1104:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1311:19)",
        "    at require (node:internal/modules/helpers:179:18)",
        "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:1)",
        "    at Module._compile (node:internal/modules/cjs/loader:1469:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)"
    ]
}
```

**Comment by jayair** [comment]
Did my examples not work?

**Comment by clemwo** [comment]
Sorry for the late reply.
I had to add this to my root `package.json` in order to get it to work:

```
  "pnpm": {
    "supportedArchitectures": {
      "cpu": ["x64", "arm64"],
      "os": ["linux", "current"]
    }
  }
```

I'm developing on MacOS, sst is version 3.1.12 and pnpm.

So I inherited the project I'm working on from other developers that have left the company already. But I think it might have worked before without my changes but after we recently deployed it broke.
I'm a beginner when it comes to serverless so I am not quite sure how this happened. But happy that it works now
