### ISSUE TITLE
SecretMissingError persists even though there is no Secret configured

### ISSUE THREAD

**Issue by TheHolyWaffle** [sst/sst#4435]
I was experimenting with using `new sst.Secret('GitlabClientSecret');`

after adding this line to `sst.config.ts` I've executed `sst dev`. Doing so shows an failure:

```
❯ sst dev
SST ❍ ion 0.0.506  ready!

➜  App:        gitlab-watcher-ion
   Stage:      bertdegeyter
   Console:    https://console.sst.dev/local/gitlab-watcher-ion/bertdegeyter

×  Failed
   SecretMissingError: Set a value for GitlabClientSecret with `sst secret set GitlabClientSecret <value>`             
       at new Secret (file:///Users/bert.degeyter/dev/gitlab-watcher-ion/.sst/platform/src/components/secret.ts:102:13)
       at run (file:///Users/bert.degeyter/dev/gitlab-watcher-ion/sst.config.ts:18:20)                                 
       at run (file:///Users/bert.degeyter/dev/gitlab-watcher-ion/.sst/platform/src/auto/run.ts:36:26)                 
       at file:///Users/bert.degeyter/dev/gitlab-watcher-ion/eval.ts:6:28                                              
       at ModuleJob.run (node:internal/modules/esm/module_job:222:25)                                                  
       at ModuleLoader.import (node:internal/modules/esm/loader:316:24) {                                              
     secretName: 'GitlabClientSecret'                                                                                  
   }

```

However, when running the command `sst secret set GitlabClientSecret foo` and then repeating the `sst dev` command continues throwing the failure even though an Secret is set.

What's worse is that after removing `new sst.Secret('GitlabClientSecret');` from `sst.config.ts` the `SecretMissingError` still persists!

I've tried deleting the sst-state folders in the S3 buckets, running `sst remove`, `sst refresh`, clearing `.sst` folder, clearing `node_modules` but nothing help.  It keeps throwing the `SecretMissingError` in `sst dev` even though there is no Secret defined in `sst.config.ts`.

**Comment by ggrantrowberry** [comment]
Was anyone able to figure this out?

**Comment by jayair** [comment]
@ggrantrowberry share more details about your error?
