### ISSUE TITLE
Nothing error on sst deploy but always interrupted

### ISSUE THREAD

**Issue by marsyofie** [sst/sst#4573]
Hello i am using [aws-nextjs example](https://github.com/sst/ion/tree/dev/examples/aws-nextjs) to try sst ion and nothing error but always interrupted, am I wrong?

here's log verbose

```
sstv3 deploy --stage staging --verbose
time=2024-05-30T11:15:27.311+07:00 level=INFO msg="checking for pulumi" path=/root/.config/sst/bin/pulumi
time=2024-05-30T11:15:27.490+07:00 level=INFO msg="checking for bun" path=/root/.config/sst/bin/bun
time=2024-05-30T11:15:27.493+07:00 level=INFO msg="initializing project" version=0.0.395
time=2024-05-30T11:15:27.493+07:00 level=INFO msg="esbuild building"
time=2024-05-30T11:15:27.495+07:00 level=INFO msg="esbuild built" outfile=/repo/ion/examples/aws-nextjs/.sst/eval/eval-1717042527493.mjs
time=2024-05-30T11:15:27.496+07:00 level=INFO msg="evaluating config"
time=2024-05-30T11:15:27.529+07:00 level=INFO msg="config evaluated"
time=2024-05-30T11:15:27.529+07:00 level=INFO msg="checking platform"
time=2024-05-30T11:15:27.529+07:00 level=INFO msg="checking provider" name=aws version=latest compare=latest
time=2024-05-30T11:15:27.530+07:00 level=INFO msg="credentials found"
time=2024-05-30T11:15:27.530+07:00 level=INFO msg="fetching bootstrap"
time=2024-05-30T11:15:27.749+07:00 level=INFO msg="found existing bootstrap" data="{\"version\":1,\"asset\":\"sst-asset-nwdrtwhuhncw\",\"state\":\"sst-state-nwdrtwhuhncw\"}"
time=2024-05-30T11:15:27.749+07:00 level=INFO msg="loaded config" app=aws-nextjs stage=staging
SST ❍ ion 0.0.395  ready!

➜  App:        aws-nextjs
   Stage:      staging

time=2024-05-30T11:15:27.749+07:00 level=INFO msg="running stack command" cmd=deploy
time=2024-05-30T11:15:27.750+07:00 level=INFO msg="INFO locking app=aws-nextjs stage=staging"
time=2024-05-30T11:15:27.750+07:00 level=INFO msg="INFO getting data key=lock app=aws-nextjs stage=staging"
time=2024-05-30T11:15:27.914+07:00 level=INFO msg="INFO putting data key=lock app=aws-nextjs stage=staging"
~  Deploying

time=2024-05-30T11:15:28.051+07:00 level=INFO msg="INFO pulling state app=aws-nextjs stage=staging out=/repo/ion/examples/aws-nextjs/.sst/.pulumi/stacks/aws-nextjs/staging.json"
time=2024-05-30T11:15:28.204+07:00 level=INFO msg="INFO getting passphrase app=aws-nextjs stage=staging"
time=2024-05-30T11:15:28.387+07:00 level=INFO msg="INFO getting data key=secret app=aws-nextjs stage=staging"
time=2024-05-30T11:15:28.519+07:00 level=INFO msg="esbuild building"
time=2024-05-30T11:15:28.577+07:00 level=INFO msg="esbuild built" outfile=/repo/ion/examples/aws-nextjs/.sst/platform/eval/eval-1717042528519.mjs
time=2024-05-30T11:15:28.577+07:00 level=INFO msg="tracked files"
time=2024-05-30T11:15:28.749+07:00 level=INFO msg="built workspace"
time=2024-05-30T11:15:28.922+07:00 level=INFO msg="built stack"
time=2024-05-30T11:15:29.111+07:00 level=INFO msg="built config"
time=2024-05-30T11:15:29.111+07:00 level=INFO msg="running stack command" cmd=deploy
time=2024-05-30T11:15:29.698+07:00 level=INFO msg="INFO putting summary app=aws-nextjs stage=staging"
time=2024-05-30T11:15:29.698+07:00 level=INFO msg="INFO putting data key=summary app=aws-nextjs stage=staging/jydpmo0jvrpcmuux41qpd1ef"
time=2024-05-30T11:15:29.846+07:00 level=INFO msg="done running stack command"
time=2024-05-30T11:15:29.846+07:00 level=INFO msg="stack command complete"

×  Interrupted

time=2024-05-30T11:15:30.186+07:00 level=INFO msg="INFO pushing state app=aws-nextjs stage=staging from=/repo/ion/examples/aws-nextjs/.sst/.pulumi/stacks/aws-nextjs/staging.json"
time=2024-05-30T11:15:30.329+07:00 level=INFO msg="INFO unlocking app=aws-nextjs stage=staging"
```

**Comment by jayair** [comment]
@bodhihawken Can you share the logs from when this happens?

**Comment by vimtor** [comment]
@thdxr suggested that I manually install Pulumi in the `/Users/user/Library/Application Support/sst/bin/`, which solved the issue.

https://github.com/pulumi/pulumi/releases

**Comment by liltechnomancer** [comment]
Still hitting this, even the manual install for pulumi didn't solve it for me. 

The logs always end like this

```
time=2024-12-16T20:38:42.616+01:00 level=INFO msg="INFO unlocking app=app-name stage=levi"
time=2024-12-16T20:38:42.993+01:00 level=INFO msg="shutting down server"
time=2024-12-16T20:38:42.993+01:00 level=INFO msg="server done"
```

Oddly enough the unlock command completes if run alone.

**Comment by arpadgabor** [comment]
A work colleague also sees exactly what @liltechnomancer shared. No errors.

**Comment by jayair** [comment]
Pinging the Dax

**Comment by thomkrupa** [comment]
Did you try upgrading to the latest version? Had this weird 'Interrupted' error on SST v3.2.40, but it started working after upgrading to v3.4.53.

**Comment by jayair** [comment]
Yeah we have been rolling out a bunch of fixes lately. So would appreciate people retrying the latest and reporting back.

**Comment by GAUKjpd** [comment]
I've upgraded today and I'm getting this on every deploy.

```
sst 3.4.56
pulumi 3.143.0
```

If I delete the config folder listed from `sst version --verbose` as suggested by @thdxr it'll work but if I then try and redeploy I get Interrupted again.  So at the moment I'm having to delete the folder for each deploy.

Edit: Seems to have resolved itself 🤷 
Edit2: Happening again now :(
Edit3: Now happening consistently, even when removing the config folder.

**Comment by abenjaminov** [comment]
I have also encountered this issue inside a github action

**Comment by jayair** [comment]
@thdxr

**Comment by dufia** [comment]
I removed .sst in my root and it fixed the problem

**Comment by imjulianeral** [comment]
I just got the same issue, no solution worked for me.

![Image](https://github.com/user-attachments/assets/7897bb15-a166-484e-9d84-d96770a4e9f8)

**Comment by imjulianeral** [comment]
> I just got the same issue, no solution worked for me.
> 
> ![Image](https://github.com/user-attachments/assets/7897bb15-a166-484e-9d84-d96770a4e9f8)

I discovered what was causing the issue. The app name can't be just a number anymore, my app name was `360` after adding a prefix it worked without issues.

Idk if this is a bug or a premeditated change.

**Comment by thdxr** [comment]
it should at least not error silently let me try to reproduce

**Comment by thdxr** [comment]
better warning in v3.11.8

**Comment by CiroGomes** [comment]
Hey guys, I'm facing the same issue, and is not because of the app name been a number. I tried everything above, but didn't wanted to recreate the stage (staging). Is there a way to do a hard reset on it? Something like removing some snapshots.

EDIT
I just found a solution. I'm not sure what was causing the issue, because a manual deploy started it, but to fix it, I did this:
I went to the `sst-state-xx` folder in S3, and then to the `snapshots` folder. There, I downloaded the latest snapshot from when SST was still working. Then, I took this JSON and replaced the one in the `app` folder. This kind of forced a hard reset.

(If we hard reset it and the new version had some new resource, it will be created again. Example: you had created `my-bucket-2`, and did the reset — it will create a second `my-bucket-2`, and you'll end up with two of them. So you need to manually go there and delete any created resources, because they will be forgotten by SST and will remain there.)

**Comment by shansmith01** [comment]
@CiroGomes I was just having the same issue a sec ago. Get your .sst>log>pulumi.eer.log.

I can't remember the message now, but it had something to do with node and the application folder.

So i did 
- SST remove on my dev stage
- Went to my Application Support folder and deleted SST
- Ran 'sst dev'

And that got me unblocked

**Comment by CiroGomes** [comment]
Hey @shansmith01 , I assume recreating the stage would work, yes, but I was trying to avoid that because it happened in my staging env, not the dev one. Recreating it would be problematic. If it had happened in the dev env, I would’ve recreated it without any problem!
The second approach I was going to try was removing it with the flag removal: 'retain' and then importing everything back, but I'm not sure if that would work.
Anyway, thank you for sharing your solution!

This is the first message in `pulumi.err.log`: `error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!`

**Comment by SolomidHero** [comment]
Got same error.

sst version: 3.13.10 (also tried 3.17.8 - same behaviour)
```
sst 3.17.8
pulumi 3.146.0
config /home/ubuntu/.config/sst
GOARCH amd64
GOOS linux
```

Deleting /home/ubuntu/.config/sst didn't help

`pulumi.err.log` shows a snapshot integrity error:
```
error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!

You can try to repair your snapshot as follows:

* Using the `pulumi state repair` command. This is the recommended approach.
  Run `pulumi state repair --help` for more information.
* Passing the `--disable-integrity-checking` flag. This will disable integrity
  checking on many Pulumi commands. This is riskier, but may allow you to
  execute fine-grained repairs using e.g. `pulumi state delete`.

================================================================================
We would appreciate a report: https://github.com/pulumi/pulumi/issues/

Please provide all of the text below in your report.
================================================================================
Go Version:        go1.23.4
Go Compiler:       gc
Architecture:      amd64
Operating System:  linux

Write Version:     v3.146.0
Write Command:     /home/ubuntu/.config/sst/bin/pulumi up --yes -f --stack organization/sst-deploy/edge --non-interactive --event-log /home/ubuntu/telephony/sst-webhooks/.sst/pulumi/fe6834959815144dc70a254e/eventlog.json --config aws:defaultTags={"tags":{"sst:app":"sst-deploy","sst:stage":"edge"}} --config aws:region=us-east-2 --target urn:pulumi:edge::sst-deploy::sst:aws:Function::MyPythonFunction --target-dependents
Write Error:       resource urn:pulumi:edge::sst-deploy::sst:aws:Cron$sst:aws:Function$docker-build:index:Image::AlertsCronHandlerImage refers to unknown provider urn:pulumi:edge::sst-deploy::pulumi:providers:docker-build::default_0_0_8::424198aa-62a9-4799-a09c-5e0ddc0cd535

Read Version:      v3.146.0
Read Command:      /home/ubuntu/.config/sst/bin/pulumi up --yes -f --stack organization/sst-deploy/edge --non-interactive --event-log /home/ubuntu/telephony/sst-webhooks/.sst/pulumi/fe6834832dece8385ad4f1f1/eventlog.json --config aws:defaultTags={"tags":{"sst:app":"sst-deploy","sst:stage":"edge"}} --config aws:region=us-east-2
Read Error:        snapshot integrity failure; refusing to use it: resource urn:pulumi:edge::sst-deploy::sst:aws:Cron$sst:aws:Function$docker-build:index:Image::AlertsCronHandlerImage refers to unknown provider urn:pulumi:edge::sst-deploy::pulumi:providers:docker-build::default_0_0_8::424198aa-62a9-4799-a09c-5e0ddc0cd535

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x2c93404?, 0xc00123d8e8?}, {0xc00123d908?, 0x51?, 0x40?})
	github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:617 +0x34
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0xc0019d00a0)
	github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:458 +0x51d
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getSnapshot(0xc0015485a0, {0x33a31d0, 0x4a68d40}, {0x337fc40, 0x4a68d40}, 0xc00155a0c0)
	github.com/pulumi/pulumi/pkg/v3/backend/diy/state.go:180 +0x125
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Snapshot(0xc001f40c60, {0x33a31d0, 0x4a68d40}, {0x337fc40, 0x4a68d40})
	github.com/pulumi/pulumi/pkg/v3/backend/diy/stack.go:62 +0x85
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getTarget(0xc0015485a0, {0x33a31d0, 0x4a68d40}, {0x337fc40, 0x4a68d40}, 0xc00155a0c0, 0xc001557aa0, {0x7fb53742a440, 0x4a68d40})
	github.com/pulumi/pulumi/pkg/v3/backend/diy/state.go:128 +0xd1
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).newUpdate(_, {_, _}, {_, _}, _, {0xc001e9d080, {0xc001247260, 0x48}, {0x0, ...}, ...})
	github.com/pulumi/pulumi/pkg/v3/backend/diy/state.go:101 +0xbd
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc001e9d080, {0xc001247260, 0x48}, ...}, ...)
	github.com/pulumi/pulumi/pkg/v3/backend/diy/backend.go:1085 +0x33e
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc001e9d080, {0xc001247260, 0x48}, {0x0, ...}, ...}, ...)
	github.com/pulumi/pulumi/pkg/v3/backend/apply.go:272 +0x22d
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).Update(_, {_, _}, {_, _}, {0xc001e9d080, {0xc001247260, 0x48}, {0x0, 0x0, ...}, ...})
	github.com/pulumi/pulumi/pkg/v3/backend/diy/backend.go:967 +0x1c5
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc001e9d080, {0xc001247260, 0x48}, {0x0, 0x0, 0x0}, ...})
	github.com/pulumi/pulumi/pkg/v3/backend/stack.go:97 +0x9e
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Update(_, {_, _}, {0xc001e9d080, {0xc001247260, 0x48}, {0x0, 0x0, 0x0}, 0xc0011eb1d0, ...})
	github.com/pulumi/pulumi/pkg/v3/backend/diy/stack.go:89 +0x6a
github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/operations.NewUpCmd.func1({_, _}, {_}, {_, _}, {_, _}, {{{0x4a68d40, 0x0, 0x0}, ...}, ...}, ...)
	github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/operations/up.go:222 +0x102d
github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/operations.NewUpCmd.func3(0xc00126a308, {0xc001e9cb00, 0x0, 0x0?})
	github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/operations/up.go:598 +0xd29
github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/operations.NewUpCmd.RunCmdFunc.func4(0x0?, {0xc001e9cb00?, 0x0?, 0x0?})
	github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/cmd/cmd.go:45 +0x1c
github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/operations.NewUpCmd.RunCmdFunc.RunFunc.func7(0xc00126a308, {0xc001e9cb00, 0x0, 0xb})
	github.com/pulumi/pulumi/sdk/v3@v3.145.0/go/common/util/cmdutil/exit.go:99 +0x3b
github.com/spf13/cobra.(*Command).execute(0xc00126a308, {0xc001e9ca50, 0xb, 0xb})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0xc001cd7208)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/main.go:55 +0x4e
```

**Comment by SolomidHero** [comment]
@thdxr @jayair 
I also tried `npx sst state repair --stage=edge --print-logs` but it errored:
```
time=2025-07-02T14:34:26.187Z level=INFO msg="checking for pulumi" path=/home/ubuntu/.config/sst/bin/pulumi
time=2025-07-02T14:34:26.481Z level=INFO msg="checking for bun" path=/home/ubuntu/.config/sst/bin/bun
time=2025-07-02T14:34:26.485Z level=INFO msg="initializing project" version=3.17.8
time=2025-07-02T14:34:26.486Z level=INFO msg="esbuild building" out=/home/ubuntu/telephony/sst-webhooks/.sst/platform/sst.config.1751466866486.mjs
time=2025-07-02T14:34:26.494Z level=INFO msg="esbuild built" outfile=/home/ubuntu/telephony/sst-webhooks/.sst/platform/sst.config.1751466866486.mjs
time=2025-07-02T14:34:26.495Z level=INFO msg="evaluating config"
time=2025-07-02T14:34:26.556Z level=INFO msg="config evaluated"
time=2025-07-02T14:34:26.557Z level=INFO msg="checking platform"
time=2025-07-02T14:34:26.557Z level=INFO msg="loading home"
time=2025-07-02T14:34:26.557Z level=INFO msg="aws credentials found" region=us-east-2 profile=intone-mfa
time=2025-07-02T14:34:26.557Z level=INFO msg="fetching bootstrap"
time=2025-07-02T14:34:26.613Z level=INFO msg="found existing bootstrap" data="{\"version\":5,\"asset\":\"sst-asset-dxumtecotsdk\",\"assetEcrRegistryId\":\"131028765235\",\"assetEcrUrl\":\"131028765235.dkr.ecr.us-east-2.amazonaws.com/sst-asset\",\"state\":\"sst-state-dxumtecotsdk\",\"appsyncHttp\":\"ru5uuzzlw5cxlamq4zklnbt7e4.appsync-api.us-east-2.amazonaws.com\",\"appsyncRealtime\":\"ru5uuzzlw5cxlamq4zklnbt7e4.appsync-realtime-api.us-east-2.amazonaws.com\"}"
time=2025-07-02T14:34:26.614Z level=INFO msg="loaded config" app=sst-deploy stage=edge
time=2025-07-02T14:34:26.614Z level=INFO msg="INFO locking app=sst-deploy stage=edge"
time=2025-07-02T14:34:26.614Z level=INFO msg="INFO getting data key=lock app=sst-deploy stage=edge"
time=2025-07-02T14:34:26.704Z level=INFO msg="INFO putting update app=sst-deploy stage=edge"
time=2025-07-02T14:34:26.749Z level=INFO msg="INFO pulling state app=sst-deploy stage=edge out=/home/ubuntu/telephony/sst-webhooks/.sst/pulumi/fe6834708849dfa4b3ef8ae4/.pulumi/stacks/sst-deploy/edge.json"
time=2025-07-02T14:34:26.847Z level=INFO msg="INFO putting update app=sst-deploy stage=edge"
time=2025-07-02T14:34:26.901Z level=INFO msg="INFO unlocking app=sst-deploy stage=edge"
time=2025-07-02T14:34:26.942Z level=ERROR msg="exited with error" err=<nil>
✕  No changes made
```

But direct unlock works fine:
```
$ npx sst unlock --stage=edge --print-logs

time=2025-07-02T14:38:11.483Z level=INFO msg="checking for pulumi" path=/home/ubuntu/.config/sst/bin/pulumi
time=2025-07-02T14:38:11.791Z level=INFO msg="checking for bun" path=/home/ubuntu/.config/sst/bin/bun
time=2025-07-02T14:38:11.794Z level=INFO msg="initializing project" version=3.17.8
time=2025-07-02T14:38:11.795Z level=INFO msg="esbuild building" out=/home/ubuntu/telephony/sst-webhooks/.sst/platform/sst.config.1751467091795.mjs
time=2025-07-02T14:38:11.801Z level=INFO msg="esbuild built" outfile=/home/ubuntu/telephony/sst-webhooks/.sst/platform/sst.config.1751467091795.mjs
time=2025-07-02T14:38:11.802Z level=INFO msg="evaluating config"
time=2025-07-02T14:38:11.857Z level=INFO msg="config evaluated"
time=2025-07-02T14:38:11.858Z level=INFO msg="checking platform"
time=2025-07-02T14:38:11.858Z level=INFO msg="loading home"
time=2025-07-02T14:38:11.859Z level=INFO msg="aws credentials found" region=us-east-2 profile=intone-mfa
time=2025-07-02T14:38:11.859Z level=INFO msg="fetching bootstrap"
time=2025-07-02T14:38:11.919Z level=INFO msg="found existing bootstrap" data="{\"version\":5,\"asset\":\"sst-asset-dxumtecotsdk\",\"assetEcrRegistryId\":\"131028765235\",\"assetEcrUrl\":\"131028765235.dkr.ecr.us-east-2.amazonaws.com/sst-asset\",\"state\":\"sst-state-dxumtecotsdk\",\"appsyncHttp\":\"ru5uuzzlw5cxlamq4zklnbt7e4.appsync-api.us-east-2.amazonaws.com\",\"appsyncRealtime\":\"ru5uuzzlw5cxlamq4zklnbt7e4.appsync-realtime-api.us-east-2.amazonaws.com\"}"
time=2025-07-02T14:38:11.920Z level=INFO msg="loaded config" app=sst-deploy stage=edge
time=2025-07-02T14:38:11.920Z level=INFO msg="INFO force unlocking app=sst-deploy stage=edge"
time=2025-07-02T14:38:11.920Z level=INFO msg="INFO getting data key=lock app=sst-deploy stage=edge"
✓  Unlocked the app state for: sst-deploy / edge
```


I believe people who got issue with number project name just got it fix, because created different app and thus stage.

**Comment by SolomidHero** [comment]
I finally fixed it by removing one of my conflicting target via `npx sst state remove <>`.
I guess I expect `state repair` at first to help with such issue. Possibly, there could be improvements to repair tool

**Comment by liltechnomancer** [comment]
Wanted to add that @SolomidHero helped me finally solve this. I just went through and removed resources with `npx sst state remove` until `sst remove --stage` worked

**Comment by cfranc0** [comment]
Hello!

I understand this issue has been closed, but I wanted to point out that I was facing an annoying version of this problem where (as others faced) running `sst unlock` reported being able to unlock the stage, but any other command (including remove) would error out with `Interrupted`.

I was able to fix the issue using the suggestion from @CiroGomes as [posted in his comment](https://github.com/sst/sst/issues/4573#issuecomment-2978558757).

To give some context as to what might have caused the issue: I was trying to introduce having 2 Route53 hosted zones for the same domain, one public and one internal. The domains are defined as:

```js
{
	name: domain,
	dns: sst.aws.dns(),
}
```

A deploy failed as soon as I tried to perform it after creating the new hosted zone; I assume the problem was that suddenly the lookup was returning a different hosted zone ID.

I'm afraid I have lost the `pulumi.err.log` file, but I remember it was reporting that a resource like `urn:pulumi:dev::***::sst:aws:ApiGatewayV2$sst:aws:Certificate$pulumi-nodejs:dynamic:Resource::<resource ID here>SslCNAMEZoneLookup8ef408eb750b9c554019fd493f8d4d4e<domain without . here>.sst.aws.HostedZoneLookup` was having some kind of issue with its provider.

I was quite confused to notice how the command that resulted in this problem always had the `--target` param passed to that command originally, although none of the subsequent requests had it. I assume SST was trying to "make up" for the failed deploy on new ones.

I now deployed again successfully with both hosted zones again defined in Route53 but, this time, specifying the ID for each one.

**Comment by tienpvse1** [comment]
> Hey guys, I'm facing the same issue, and is not because of the app name been a number. I tried everything above, but didn't wanted to recreate the stage (staging). Is there a way to do a hard reset on it? Something like removing some snapshots.
> 
> EDIT I just found a solution. I'm not sure what was causing the issue, because a manual deploy started it, but to fix it, I did this: I went to the `sst-state-xx` folder in S3, and then to the `snapshots` folder. There, I downloaded the latest snapshot from when SST was still working. Then, I took this JSON and replaced the one in the `app` folder. This kind of forced a hard reset.
> 
> (If we hard reset it and the new version had some new resource, it will be created again. Example: you had created `my-bucket-2`, and did the reset — it will create a second `my-bucket-2`, and you'll end up with two of them. So you need to manually go there and delete any created resources, because they will be forgotten by SST and will remain there.)

thanks, I solved the issue using your solution 🚀 life saver

**Comment by ChrisGrigg** [comment]
sst state repair

**Comment by jonathanbiard** [comment]
> Hey guys, I'm facing the same issue, and is not because of the app name been a number. I tried everything above, but didn't wanted to recreate the stage (staging). Is there a way to do a hard reset on it? Something like removing some snapshots.
> 
> EDIT I just found a solution. I'm not sure what was causing the issue, because a manual deploy started it, but to fix it, I did this: I went to the `sst-state-xx` folder in S3, and then to the `snapshots` folder. There, I downloaded the latest snapshot from when SST was still working. Then, I took this JSON and replaced the one in the `app` folder. This kind of forced a hard reset.
> 
> (If we hard reset it and the new version had some new resource, it will be created again. Example: you had created `my-bucket-2`, and did the reset — it will create a second `my-bucket-2`, and you'll end up with two of them. So you need to manually go there and delete any created resources, because they will be forgotten by SST and will remain there.)

Worked for me! Thanks for sharing your solution! 🥇 

_Note: sst state repair did not fix the issue for me._
