### ISSUE TITLE
Support Lambda@Edge for `sst start`

### ISSUE THREAD

**Issue by fwang** [sst/sst#577]
Currently `sst start` sets the websocket endpoint as environment variables for the stub Lambda functions. Lambda@Edge functions do not support environment variables. Need to use other ways to pass the information in:

### Possible solution 1
Pass information in via origin headers - https://stackoverflow.com/questions/54828808/aws-lambdaedge-nodejs-environment-variables-are-not-supported

### Possible solution 2
Add to the beginning of the handler file:
```js
process.env.SST_DEBUG_ENDPOINT=wss://...
```

### Possible solution 3
Dynamically replace placeholder values `{{ SST_DEBUG_ENDPOINT }}` with actual value on deploy using custom resource. Similar to `NextjsSite`.

---
Requests:
- Louis https://serverless-stack.slack.com/archives/C01JG3B20RY/p1626989430344800
- Dan & Devin https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645038380832099
- Tim V https://serverless-stack.slack.com/archives/C01JG3B20RY/p1646155346534409?thread_ts=1646155315.654809&cid=C01JG3B20RY
- Jack https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1649693274122179

**Comment by joquijada** [comment]
What's the word on this request? Is there a work around to running Lambda@Edge's in live environment via `sst start`? I get this error because of environment variables that SST sets in the `new Function(...)` construct:

```
Error: Resolution error: Resolution error: Resolution error: The function bob-niko-stack-AcmeEdgeStack/acmeEdgeOriginRequestLambda contains environment variables [SST_DEBUG_SRC_PATH,SST_DEBUG_SRC_HANDLER,SST_DEBUG_ENDPOINT,SST_DEBUG_BUCKET_NAME,SST_FUNCTION_ID] and is not compatible with Lambda@Edge. Environment variables can be marked for removal when used in Lambda@Edge by setting the 'removeInEdge' property in the 'addEnvironment()' API..
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces..
    at Function._checkEdgeCompatibility (/Users/bob/git/niko-stack/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:15019)
    at Object.produce (/Users/bob/git/niko-stack/node_modules/aws-cdk-lib/aws-lambda/lib/lambda-version.js:1:4529)
    at LazyString.resolve (/Users/bob/git/niko-stack/node_modules/aws-cdk-lib/core/lib/lazy.js:1:3889)
    at RememberingTokenResolver.resolveToken (/Users/bob/git/niko-stack/node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1238)
    at RememberingTokenResolver.resolveToken (/Users/bob/git/niko-stack/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:4058)
    at resolve (/Users/bob/git/niko-stack/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2661)
    at Object.resolve [as mapToken] (/Users/bob/git/niko-stack/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1121)
    at TokenizedStringFragments.mapTokens (/Users/bobgit/niko-stack/node_modules/aws-cdk-lib/core/lib/string-fragments.js:1:1365)
    at RememberingTokenResolver.resolveString (/Users/bob/git/niko-stack/node_modules/aws-cdk-lib/core/lib/resolvable.js:4:358)
    at RememberingTokenResolver.resolveString (/Users/bob/git/niko-stack/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:4134)



There was an error synthesizing your app.
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
