### ISSUE TITLE
Can't Debug in VSCode - timeout after 10000ms ECONNREFUSED

### ISSUE THREAD

**Issue by ColinCee** [sst/sst#630]
Hello 👋, loving serverless stack however I can't seem the get the debugging working on vscode.
Following the docs here https://docs.serverless-stack.com/debugging-with-vscode

Copy and pasted both configs results in both configs to produce this message, even after upping the timeout to 20k ms
![image](https://user-images.githubusercontent.com/11246116/127850208-ce18361f-e1dd-4657-9375-86f455c66b5e.png)

**Comment by fwang** [comment]
Hey @ColinCee, can you give the example a try and see if VSCode connects for you - https://github.com/serverless-stack/serverless-stack/tree/master/examples/vscode

**Comment by ColinCee** [comment]
@fwang Apologies just got round to trying out the example you suggested

Tried both `yarn` and `npm i`

Error when getting to the linting

```bash
===============
 Deploying app
===============

Preparing your SST app
Detected tsconfig.json
Transpiling source
Linting source
Error: Failed to load parser '@typescript-eslint/parser' declared in '../../../../../.eslintrc.json#overrides[0]': Cannot find module '@typescript-eslint/parser'
Require stack:
- /Users/colincheung/Code/serverless-stack/.eslintrc.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at Object.resolve (/Users/colincheung/Code/serverless-stack/examples/vscode/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadParser (/Users/colincheung/Code/serverless-stack/examples/vscode/node_modules/@eslint/eslintrc/lib/config-array-factory.js:929:45)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/colincheung/Code/serverless-stack/examples/vscode/node_modules/@eslint/eslintrc/lib/config-array-factory.js:724:43)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/colincheung/Code/serverless-stack/examples/vscode/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/colincheung/Code/serverless-stack/examples/vscode/node_modules/@eslint/eslintrc/lib/config-array-factory.js:758:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/colincheung/Code/serverless-stack/.eslintrc.json' ]
}
Running type checker
There was a problem linting the source.
```

I shouldn't need an `.eslintrc.json` right?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
