### ISSUE TITLE
Cannot find a handler file for main.go

### ISSUE THREAD

**Issue by joekendal** [sst/sst#868]
There is an issue with running Jest and `new sst.Function`. For some reason this works fine when deploying, but sst struggles to bundle the function with test setups

```bash
$ npx sst test
Preparing your SST app
Detected tsconfig.json
Transpiling source
Linting source
Running type checker
 FAIL  test/AuthStack.test.ts
  AWS::Cognito::UserPool
    ✕ UserPool Created (3 ms)

  ● AWS::Cognito::UserPool › UserPool Created

    Cannot find a handler file for "/{pathToProject}/functions/pre-signup/main.go".

       7 |      
     > 8 |     const preSignUp = new sst.Function(this, 'PreSignup', {
         |                       ^
      10 |       srcPath: path.join(__dirname, '../functions/pre-signup'),
      11 |       handler: 'main.go'
      12 |     });

      at Object.builder (node_modules/@serverless-stack/resources/src/util/nodeBuilder.ts:147:11)
      at new Function (node_modules/@serverless-stack/resources/src/Function.ts:325:21)
      at new AuthStack (stacks/Auth.ts:20:23)
      at Object.<anonymous> (test/AuthStack.test.ts:12:11)
```

#### Project layout
```sh
functions/
  pre-signup/
    main.go

stacks/
  index.ts
  AuthStack.ts

test/
  AuthStack.test.ts
```

#### stacks/AuthStack.ts
```ts
import * as sst from "@serverless-stack/resources"
import * as path from "path"

export default class AuthStack extends sst.Stack {
  constructor(scope: sst.App, id: string, props?: sst.StackProps){
    super(scope, id, props);

    const preSignUp = new sst.Function(this, 'PreSignUp', {
      srcPath: path.join(__dirname, '../functions/pre-signup'),
      handler: 'main.go'
    });
  }
}
```

#### test/AuthStack.test.ts
```ts
import { expect as expectCDK } from "@aws-cdk/assert";
import * as sst from "@serverless-stack/resources";
import AuthStack from "../stacks/Auth";


let app: sst.App;
let stack: sst.Stack;

// setup
beforeAll(() => {
  app = new sst.App();
  stack = new AuthStack(app, 'TestAuth');
});

// any test will throw error
test('UserPool Created', () => {
  expectCDK(stack).to(countResources('AWS::Cognito::UserPool', 1));
});
```

**Comment by fwang** [comment]
Hey @joekendal, thanks for bringing this up. I'm going to give it a try this week.

**Comment by joekendal** [comment]
For some reason switching from cdk cognito UserPool to sst cognito fixed this error.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
